<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_assetType</name>
   <tag></tag>
   <elementGuidId>55e65538-15cf-4347-894b-36222e341d62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#assetType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='assetType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d4ff5e4-252e-4228-911f-91e72317f885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input tableInput</value>
      <webElementGuid>c9b8e165-62f0-426a-94b9-b9c7c66dd0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb29907b-9ce1-41e7-82f4-ca8edac66b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assetType</value>
      <webElementGuid>f4f98c9d-957b-4f2a-b4b4-0f00b2e18752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Asset Type</value>
      <webElementGuid>f428c6d5-bb51-4e75-b877-72b8dcdf2a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assetType</value>
      <webElementGuid>d9a5e7d5-dfd5-4f21-b47c-2c796053082d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assetType&quot;)</value>
      <webElementGuid>2966e400-b39b-40fa-9c35-dac1dbb86647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='assetType']</value>
      <webElementGuid>251fee17-99b1-49e4-911b-4eb8811b1cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div[2]/div/table/thead/tr[2]/th[3]/span/input</value>
      <webElementGuid>9f874bd7-5d66-466b-a026-e3b3dfe4829d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span/input</value>
      <webElementGuid>4acb11d5-b3ba-40e9-8303-6ce8319c91ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'assetType' and @placeholder = 'Asset Type' and @id = 'assetType']</value>
      <webElementGuid>435df8f2-0e1a-417d-a049-16861c619976</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
