<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_employeeType</name>
   <tag></tag>
   <elementGuidId>aca1d1ef-161d-480c-9432-884599561bc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employeeType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employeeType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>738be5dd-eb76-4c13-927c-0c69fdf57c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input tableInput</value>
      <webElementGuid>5ebd1af7-4a64-463b-96da-3fb4539b7c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72229722-8153-4410-a6d1-123f6bf76195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employeeType</value>
      <webElementGuid>2ae7200c-e510-4d6b-9809-8b21de4292a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Employee Type</value>
      <webElementGuid>7ea42a64-f6e6-4db1-bfe3-3fef2789072f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employeeType</value>
      <webElementGuid>43b28e39-859c-4fd7-878a-97ae5d4590d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeType&quot;)</value>
      <webElementGuid>3fbee3ac-a6fe-4321-8ce5-c3b169dc3e5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employeeType']</value>
      <webElementGuid>5de7245d-8a8b-4b43-88db-527b74db56bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div[2]/div/table/thead/tr[2]/th[3]/span/input</value>
      <webElementGuid>067a474d-eaa0-4e54-b281-0ada16de59d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span/input</value>
      <webElementGuid>edba4ffe-c917-4749-91ea-e28026026082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'employeeType' and @placeholder = 'Employee Type' and @id = 'employeeType']</value>
      <webElementGuid>b819c9c7-80a8-4427-8cd1-50a06c085c11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
