<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_workorderStatus</name>
   <tag></tag>
   <elementGuidId>a4ae06f3-a6bd-463b-96c6-62a58751c140</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workorderStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workorderStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3064e19-4cac-4313-90d1-004a878417a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input tableInput</value>
      <webElementGuid>20aac5a0-7f96-4d0f-b217-d9b950c1d601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf312e9d-bffa-4e1a-a547-8aab310a5e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>workorderStatus</value>
      <webElementGuid>34f1c507-1da0-41c3-8e79-2c82d73e9cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Work Order Status</value>
      <webElementGuid>6eba1ccb-7d7b-4248-8bce-f8b3dde9d4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workorderStatus</value>
      <webElementGuid>7a2779fd-211a-4917-9c90-0164a440d2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workorderStatus&quot;)</value>
      <webElementGuid>0a96c064-134b-4223-9c33-2f390b3c403a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workorderStatus']</value>
      <webElementGuid>9fa96ea0-2b85-419d-9249-6852fd159841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div[2]/div/table/thead/tr[2]/th[3]/span/input</value>
      <webElementGuid>746b4b7f-0d1e-49e6-927e-ed45f8b2f8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span/input</value>
      <webElementGuid>c565da6c-b50e-434f-8dfb-3f34075cd4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'workorderStatus' and @placeholder = 'Work Order Status' and @id = 'workorderStatus']</value>
      <webElementGuid>c0f38566-89ec-4e90-8978-82deabf0465c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
