<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dashboard</name>
   <tag></tag>
   <elementGuidId>5799ca7f-f849-4ffd-8372-bd3964cbe618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.tabName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='/driver-pay/dashboard']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2c161d4-e906-4d9e-88c5-9351f6de3809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabName</value>
      <webElementGuid>6e188f83-3ae8-4966-bcd1-4debf4a29588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard   </value>
      <webElementGuid>992fd757-2964-4aff-b540-784dfe36e0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;/driver-pay/dashboard&quot;)/span[@class=&quot;tabName&quot;]</value>
      <webElementGuid>970be3e3-e1b3-4187-95c4-0f6ea3576655</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='/driver-pay/dashboard']/span</value>
      <webElementGuid>18b5a04a-5d17-45a5-b46a-8f1cb9e156f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span</value>
      <webElementGuid>eeba6a3b-999c-4fda-b3a1-1a9c88ecfb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Dashboard   ' or . = 'Dashboard   ')]</value>
      <webElementGuid>6d1e5270-c37e-4129-9574-3f8ab65acd4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
