<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>f5f9448d-797b-42d5-a0a2-03c3ea8958fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#undefined_undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='undefined_undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86cbed4b-5c30-4d2f-bfb2-50290bd2f2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cscsButton cscsButton addCscsButton</value>
      <webElementGuid>d149f38e-6c98-4bb8-867e-cebd38fc7b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefined_undefined</value>
      <webElementGuid>89a539df-4f0e-4267-88a6-2569c8e87e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>662a7482-d937-45e1-8092-49cd2dec7c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;undefined_undefined&quot;)</value>
      <webElementGuid>a0687f02-d803-4777-8c1c-72e61f73c7dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='undefined_undefined']</value>
      <webElementGuid>4f64aba4-6daf-493b-8f40-3537574cb2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[3]/div/div/button</value>
      <webElementGuid>d667b9d9-8753-4da3-9074-e3726afe4912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>2c7c0632-2400-4e35-a358-b0c8e0cc111f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'undefined_undefined' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>1f81fe12-503a-40f0-9d9e-4e3e6f472e21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
