<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_reportedBy</name>
   <tag></tag>
   <elementGuidId>dae91933-722b-4f7b-ad69-077e6cb51143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reportedBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reportedBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33b5b1a0-4d06-47c7-81cd-49dd67abcf97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>9ef1eb21-5c36-48f7-9dca-31eb1bcdd021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d03a9ee4-b1eb-49b3-8643-a872ea911d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reportedBy</value>
      <webElementGuid>542012bd-adb5-4ce2-a61b-622ee3e031d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reported By</value>
      <webElementGuid>0364cc69-e55d-459d-97d7-da884fb1afb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reportedBy</value>
      <webElementGuid>4184c828-cc11-469f-9dad-26d891abdb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportedBy&quot;)</value>
      <webElementGuid>ad2f4160-1fa0-492f-aa72-28ba27eea623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reportedBy']</value>
      <webElementGuid>d77db66e-92f6-4161-aaa9-9844d17770e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[4]/span/input</value>
      <webElementGuid>2614fc15-c27e-463e-b71a-08e8949a7493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>ebd0dbbd-e3e4-468b-b6b1-1debab829a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'reportedBy' and @placeholder = 'Reported By' and @id = 'reportedBy']</value>
      <webElementGuid>448e3039-09dc-4687-9bb8-6ca2e20162e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
