<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectLowMediumHighVery High</name>
   <tag></tag>
   <elementGuidId>8ad7fde4-6d46-4d56-91b1-ca2f941f05f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#priority</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='priority']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a233d6d6-f7c9-400e-9566-9469b64ec01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>56eea93b-1eb8-43e1-b4a1-60dfd14b37ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>priority</value>
      <webElementGuid>44923070-2ca8-4548-afac-e41471a272ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priority</value>
      <webElementGuid>81b3d603-d75c-4212-866e-92b7b38d75f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectLowMediumHighVery High</value>
      <webElementGuid>84108b83-7cd5-43be-b538-93192973e107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;priority&quot;)</value>
      <webElementGuid>f6253bcf-96ab-46fa-a4af-d1a9ffed9050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='priority']</value>
      <webElementGuid>905a1edc-2a48-45ca-b9e0-2b558d0bc406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[6]/span/select</value>
      <webElementGuid>94f8e879-e1da-4800-af74-aa7031e30d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/select</value>
      <webElementGuid>fcf8ab9f-6ab1-44d5-8a01-aff9aa757ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'priority' and @id = 'priority' and (text() = 'SelectLowMediumHighVery High' or . = 'SelectLowMediumHighVery High')]</value>
      <webElementGuid>b9cd8a0d-a0af-41b2-8463-95fe96616383</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
