<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OneTwoThreeFourFiveSix</name>
   <tag></tag>
   <elementGuidId>23dc6bc9-f41f-466f-8527-6abbbccc2d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demo-tabpane-list']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vertical-list-container.mt-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>601647af-1b6c-44cc-8659-34b0cc4b14aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vertical-list-container mt-4</value>
      <webElementGuid>5e849c46-3e7c-426b-84ce-de180a4254bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OneTwoThreeFourFiveSix</value>
      <webElementGuid>7a4aa460-1902-49cc-9ebe-398a2256ff98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-tabpane-list&quot;)/div[@class=&quot;vertical-list-container mt-4&quot;]</value>
      <webElementGuid>164af307-3b26-45bb-8762-41979a965b43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo-tabpane-list']/div</value>
      <webElementGuid>02600bdb-e8e1-42bb-a54a-f06caf9ecb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div</value>
      <webElementGuid>e7ea6a92-f8ca-46f6-a455-b46eeaf5feed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OneTwoThreeFourFiveSix' or . = 'OneTwoThreeFourFiveSix')]</value>
      <webElementGuid>e3879eae-4d37-46a0-9587-f188db8be2f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
