<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Watch</name>
   <tag></tag>
   <elementGuidId>a2fa39b8-884b-4fba-bc7e-fff3a4df9566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-79']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-79 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3665d2f6-5639-4cc3-92b0-4c8e873bd629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://estreamly.com/watch</value>
      <webElementGuid>f0afb6ae-0089-4a20-81c5-57d56576a06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watch</value>
      <webElementGuid>04fd4d76-4119-466c-ae17-a9a90c78aba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-79&quot;)/a[1]</value>
      <webElementGuid>87ade890-cd06-4bb5-9d3f-344e5200d71d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-79']/a</value>
      <webElementGuid>17c52edd-3389-4f2d-a884-263afe2a5803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Watch')]</value>
      <webElementGuid>b3e27448-4563-434f-a35c-ed6426870f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://estreamly.com/watch')]</value>
      <webElementGuid>6025cbd6-f5e8-4945-bd0e-e86226ea097f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>71bbcb07-a602-4131-bef0-6d19dd9e5a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://estreamly.com/watch' and (text() = 'Watch' or . = 'Watch')]</value>
      <webElementGuid>b3510638-8d6b-4eef-9704-5bd74b984289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
