<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LOGIN</name>
   <tag></tag>
   <elementGuidId>619aef3a-c8aa-496c-b452-4d8f80f9019f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.w-100.border-0.text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>687c8150-54ed-42ac-b0b2-055b0fcfbc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f312e859-4d7a-4e2d-b838-04f96b16dd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary w-100 border-0 text-white</value>
      <webElementGuid>f1420c81-6aa8-4295-8c6c-420406d0dc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>4accf957-48b2-4cee-a95d-b899215b3f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;row w-100 vh-100 m-0&quot;]/div[@class=&quot;col-6 p-0&quot;]/div[@class=&quot;mb-5&quot;]/form[@class=&quot;row g-3&quot;]/div[@class=&quot;mt-5 mb-3 px-5&quot;]/button[@class=&quot;btn btn-primary w-100 border-0 text-white&quot;]</value>
      <webElementGuid>3bff9c3f-cfdc-45df-84b1-19efea7845ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>ac932bde-efc3-40a8-aa84-d9d8938e2e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/form/div[3]/button</value>
      <webElementGuid>f8032716-9828-495d-9510-f99b58b7d9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0b878c72-8d31-4fc1-98c3-daea4d966ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>e7a90ebd-5d3b-4aa4-b3cf-ae5dd12b1bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
