<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Liveshopping</name>
   <tag></tag>
   <elementGuidId>280ea364-0878-415c-b874-de9c7cec802d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-811']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-811 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b765c191-70df-4168-9098-bc5f61c1bfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://get.estreamly.com/liveshopping/</value>
      <webElementGuid>b8aae8cf-ab9c-4e32-99dc-ba15050d351a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Liveshopping</value>
      <webElementGuid>abdb436d-542c-4f9f-b6bd-8af6a68ad198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-811&quot;)/a[1]</value>
      <webElementGuid>739b97c3-4e84-496c-b932-1622c9b4f581</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-811']/a</value>
      <webElementGuid>fd5b47d5-4f1a-4c32-9827-5408be14aab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Liveshopping')]</value>
      <webElementGuid>ffd3767f-00a6-42dd-9e65-9dea9aa72a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://get.estreamly.com/liveshopping/')]</value>
      <webElementGuid>a0d93a36-3609-4817-a8af-fa903a141b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>7712e60c-d8bb-4b66-9cb5-56bd3d82b132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://get.estreamly.com/liveshopping/' and (text() = 'Liveshopping' or . = 'Liveshopping')]</value>
      <webElementGuid>af4d8dae-d6fa-4502-af8f-d86a711e1a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
