<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Alert</name>
   <tag></tag>
   <elementGuidId>c22f5216-0480-4fbe-bc5c-0e354e10b471</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='myFunctionAlert()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HTML9 > div.widget-content > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>864e7c5a-cb62-49f8-a4ea-52efc2c2cffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>myFunctionAlert()</value>
      <webElementGuid>9373ad90-2861-4030-81b6-ad58d84068ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alert</value>
      <webElementGuid>1e1cbcb3-92e9-4081-a264-17b131de2b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HTML9&quot;)/div[@class=&quot;widget-content&quot;]/button[1]</value>
      <webElementGuid>9915dcab-f9df-4864-85de-9c11dd62ae50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='myFunctionAlert()']</value>
      <webElementGuid>2f4ac5c1-fb72-4235-9cab-bba1e01834a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HTML9']/div/button</value>
      <webElementGuid>c1d46481-6bc3-432f-b66b-c6f5fa7cf260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>f029b068-bde6-465f-b9e9-11b2eab8c5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Alert' or . = 'Alert')]</value>
      <webElementGuid>bfda17d1-adaa-497f-a0a0-a3b3e23e8a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
