<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Prompt</name>
   <tag></tag>
   <elementGuidId>e9e783b8-ca08-4e63-933c-cf17fa20be4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='myFunctionPrompt()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f73bade-e833-48ef-9e73-6df3b7106f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>myFunctionPrompt()</value>
      <webElementGuid>d9abfd82-a5ba-412d-9e87-7049a0ec297b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prompt</value>
      <webElementGuid>85d02e44-7044-42a4-972e-f9afc70351f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HTML9&quot;)/div[@class=&quot;widget-content&quot;]/button[3]</value>
      <webElementGuid>565a31ea-a978-43e5-8c0e-faa7fb633d18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='myFunctionPrompt()']</value>
      <webElementGuid>c12815b5-62d2-441e-b4cf-0fe85932067c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HTML9']/div/button[3]</value>
      <webElementGuid>b6b2d7c9-c7ae-45d6-97ab-5316eebf0e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>0213d871-417f-4a3d-ada5-b09719df994d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Prompt' or . = 'Prompt')]</value>
      <webElementGuid>9c0a4448-07e8-4909-b121-1132f7debfc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
