<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm Box</name>
   <tag></tag>
   <elementGuidId>337cd7bc-47ed-44ba-b175-228062bf4067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='myFunctionConfirm()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d81ab4e-c513-495f-9de1-cc2d771a7297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>myFunctionConfirm()</value>
      <webElementGuid>ed42b1bd-9ae5-4b1b-9107-3881e94ad1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm Box</value>
      <webElementGuid>ea38ac20-61fb-46f2-919a-b8e6591f372c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HTML9&quot;)/div[@class=&quot;widget-content&quot;]/button[2]</value>
      <webElementGuid>8da1549d-9e34-4e25-957a-7817881d1f15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='myFunctionConfirm()']</value>
      <webElementGuid>2ab94a1b-225f-48bb-93d3-93fa805638ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HTML9']/div/button[2]</value>
      <webElementGuid>f26b7bef-7dc7-4da1-83d4-f270bbeaf94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>9144b38b-5d4c-4bad-8ec6-81aaaf71cd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Confirm Box' or . = 'Confirm Box')]</value>
      <webElementGuid>667edc60-ef87-492d-a0b4-114d0550da8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
