<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Draw a polygon</name>
   <tag></tag>
   <elementGuidId>1aebc545-d108-492b-ad28-63ccc90e5db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.leaflet-draw-draw-polygon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d73d0a21-5801-41bb-ba4e-4f5ee4b92dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-draw-draw-polygon</value>
      <webElementGuid>6e2a4443-b80e-4c06-9060-20045cad0d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>51f5efa0-6b11-4e98-a80a-1dd88fb7ce00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Draw a polygon</value>
      <webElementGuid>bf3d8c5c-4081-4e35-8803-37a97e027be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draw a polygon</value>
      <webElementGuid>c544d6d4-22b7-44d0-a3db-b1060b5d6f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/div[@class=&quot;sidePage&quot;]/div[@class=&quot;sidebody&quot;]/div[1]/div[@class=&quot;borderWrapper&quot;]/div[@class=&quot;leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom&quot;]/div[@class=&quot;leaflet-control-container&quot;]/div[@class=&quot;leaflet-top leaflet-right&quot;]/div[@class=&quot;leaflet-draw leaflet-control&quot;]/div[@class=&quot;leaflet-draw-section&quot;]/div[@class=&quot;leaflet-draw-toolbar leaflet-bar leaflet-draw-toolbar-top&quot;]/a[@class=&quot;leaflet-draw-draw-polygon&quot;]</value>
      <webElementGuid>69aff04d-9b39-48b7-93f6-14746dd520fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div/div/a</value>
      <webElementGuid>cea15151-20cb-41fc-a624-d6213cf730a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>451b284d-e355-4fad-a72c-5de6af406543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/a</value>
      <webElementGuid>9caf19b5-2178-4bf4-be00-959130174591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Draw a polygon' and (text() = 'Draw a polygon' or . = 'Draw a polygon')]</value>
      <webElementGuid>e3621c01-f412-4f95-b698-0c62a6b265b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
