<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select Person</name>
   <tag></tag>
   <elementGuidId>c0044a3c-26fb-41a8-8c4d-30ac46e9367d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#undefined_undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='undefined_undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>acfd0e4c-cfe5-4070-8bbe-7e741d839793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cscsButton </value>
      <webElementGuid>e23624e3-7ee1-4893-8989-5310c458df58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefined_undefined</value>
      <webElementGuid>7d22d95f-d7b5-44c0-a3ec-748a13dd6f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Person</value>
      <webElementGuid>49d4aa2e-a12c-4347-bbf1-2dc884f2cf07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/div[@class=&quot;sidePage&quot;]/div[@class=&quot;sidebody&quot;]/div[@class=&quot;borderWrapper&quot;]/div[@class=&quot;d-flex flex-wrap justify-content-between&quot;]/div[@class=&quot;flex-md-fill flex-sm-fill&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/div[@class=&quot;m-3&quot;]/div[@class=&quot;buttonGroup mb-1&quot;]/div[1]/button[@id=&quot;undefined_undefined&quot;]</value>
      <webElementGuid>26aa0a24-5890-4f14-9122-d3b04ecf1bac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='undefined_undefined']</value>
      <webElementGuid>63905207-ad59-423c-a3af-65bb3292d287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>0d62e9f8-457c-4e8c-b464-6dd26957e816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button</value>
      <webElementGuid>5849c089-c70a-4df3-8dfa-a8a53b5497c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'undefined_undefined' and (text() = 'Select Person' or . = 'Select Person')]</value>
      <webElementGuid>26001b2b-4085-4bb5-af60-8de644a04f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
