<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Assign</name>
   <tag></tag>
   <elementGuidId>032ee6c0-0464-4c33-80ef-ca1ff38b1928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#undefined_undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='undefined_undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86999f07-4179-4822-aa2d-cdf266ebf990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cscsButton </value>
      <webElementGuid>bbd90e35-c9f1-4268-84a4-41b6e5316ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefined_undefined</value>
      <webElementGuid>0dc89b57-b485-4886-b524-e367370580a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assign</value>
      <webElementGuid>e1a77c50-4a6b-4d46-97ec-a24e79b0a04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/div[@class=&quot;sidePage&quot;]/div[@class=&quot;sidebody&quot;]/div[@class=&quot;assetAssignment-container&quot;]/div[@class=&quot;asset-container&quot;]/div[@class=&quot;assetWrapper&quot;]/div[@class=&quot;customViewWrapper&quot;]/div[@class=&quot;customViewFieldWrapper2&quot;]/div[1]/button[@id=&quot;undefined_undefined&quot;]</value>
      <webElementGuid>d79280a6-37ab-4a3f-9df5-bccc4162bb88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='undefined_undefined']</value>
      <webElementGuid>056222c7-4810-47e9-ac49-bf4a396fcf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[3]/div/div/div[5]/div/button</value>
      <webElementGuid>723c2df0-343d-4f16-af1f-5702ab48bb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>65121a6b-3062-4417-b804-60302aaa0ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'undefined_undefined' and (text() = 'Assign' or . = 'Assign')]</value>
      <webElementGuid>3ae2958b-7df7-428e-bf96-8267fff4c2b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
