<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1268, randomProjectName</name>
   <tag></tag>
   <elementGuidId>1bb74327-8073-4ab8-8e6a-87e8f3eb007d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-8-option-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-8-option-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bedf973e-4c29-4fe0-89c2-491b2a6f1752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-a40s02-option</value>
      <webElementGuid>f815ebad-08c1-4531-818d-bee3d5e564e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>59e315df-4eba-4e3a-8788-93bb149253a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-8-option-8</value>
      <webElementGuid>0a33c977-fcfd-4d5c-814e-7ecc50ba2611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3394fe12-1f7a-44ab-8d67-e846dcf696d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1268, randomProjectName</value>
      <webElementGuid>c2976d83-54f6-47b7-a834-69651e8047c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-8-option-8&quot;)</value>
      <webElementGuid>dbc4b218-745e-4c21-83a6-bace557e0056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-8-option-8']</value>
      <webElementGuid>24b87a03-d6af-4cdb-9d7e-402ef56822c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-8-listbox']/div/div[9]</value>
      <webElementGuid>e605d230-8a08-41a4-85d3-b2e68a4b3fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]</value>
      <webElementGuid>79e4682a-ccfe-4050-bfe9-8dcae5761f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-8-option-8' and (text() = '1268, randomProjectName' or . = '1268, randomProjectName')]</value>
      <webElementGuid>4620ced0-04cb-43db-ae22-0e932cb9240c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
