<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit Geofence houston234 Name Edit laye_70ed0e</name>
   <tag></tag>
   <elementGuidId>121d606e-dab2-40b4-b113-c0f175f05bb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sidebody</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19dd6f7d-13f4-4876-9fda-a421f45179bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebody</value>
      <webElementGuid>7c9dd110-19b9-414d-9099-3e6dfe7a3236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Geofence houston234 Name *+−Edit layersDelete layers Leaflet | © OpenStreetMapUpdate</value>
      <webElementGuid>7939551a-bcb9-4913-8a6f-c399321e87a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/div[@class=&quot;sidePage&quot;]/div[@class=&quot;sidebody&quot;]</value>
      <webElementGuid>41ab72aa-0516-437a-a277-0778f4f27454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]</value>
      <webElementGuid>eea2937d-8512-4c44-aae5-f48e11871bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>66182a88-e738-43b6-805a-542391a5827b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Edit Geofence houston234 Name *+−Edit layersDelete layers Leaflet | © OpenStreetMapUpdate' or . = 'Edit Geofence houston234 Name *+−Edit layersDelete layers Leaflet | © OpenStreetMapUpdate')]</value>
      <webElementGuid>5fbcb567-ed16-46e1-bc3b-2f3570c7b38f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
