<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_kaurugh, kdfg</name>
   <tag></tag>
   <elementGuidId>71822079-4442-40ca-b9a2-0a2ff378b668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-25-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-25-option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90e0083a-fbc6-47d8-9961-b5c4b37e2cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-a40s02-option</value>
      <webElementGuid>b5ba84f6-7948-4313-b2f4-a10486ca6ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3c6d9fb-b4bc-4354-b20c-5cd49f8159d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-25-option-1</value>
      <webElementGuid>a9740329-79f5-4927-83af-978c5f3c2ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>521d7944-f088-4ea0-bc7e-e6e3eed38bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>kaurugh, kdfg</value>
      <webElementGuid>b2166d9a-6ca2-4fb9-aea1-6b7ab7b2bae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-25-option-1&quot;)</value>
      <webElementGuid>d867f169-99e5-403b-b6cd-2c87cca76f5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-25-option-1']</value>
      <webElementGuid>37b97bdf-cb27-4d23-8865-d8da2e88e636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-25-listbox']/div/div[2]</value>
      <webElementGuid>5bf0dea4-018b-46d9-9568-810045e37a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div[2]</value>
      <webElementGuid>6fc0fb96-86b0-4bb4-a4ed-cf2a4909e289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-25-option-1' and (text() = 'kaurugh, kdfg' or . = 'kaurugh, kdfg')]</value>
      <webElementGuid>df9f08e5-bc48-4683-b00f-ec6e86e9dbc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
