<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_plannedCost</name>
   <tag></tag>
   <elementGuidId>944c49db-8e82-4874-a1b4-66c211c9b71a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#plannedCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plannedCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>049fccf9-e399-443c-94f9-55dcd3e22f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input tableInput</value>
      <webElementGuid>423c32e7-03b3-40e6-8014-52098615d814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c9274120-de8f-4019-af2f-8951f7334d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>plannedCost</value>
      <webElementGuid>c8eb4abd-b7f3-43fc-9dbc-1bcbf03a9a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Planned Asset Cost</value>
      <webElementGuid>1e4e6a2e-1ee5-4376-8353-54d7aee37a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plannedCost</value>
      <webElementGuid>a1ae5b9e-2b01-4419-8a2c-ff86695de418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plannedCost&quot;)</value>
      <webElementGuid>b735cb92-4872-426f-b6df-4934ceefa35d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plannedCost']</value>
      <webElementGuid>4b3ed8e0-803d-4d97-a31a-900441c6929a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[4]/div/div[2]/div/div/div[2]/div/table/thead/tr[2]/th[5]/span/input</value>
      <webElementGuid>6a23171c-cdec-4151-a9a1-15e0b77479f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/span/input</value>
      <webElementGuid>74685d65-fc76-4752-8c7c-03b90b0aa923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'plannedCost' and @placeholder = 'Planned Asset Cost' and @id = 'plannedCost']</value>
      <webElementGuid>21eab987-7b09-471b-bb13-878347a47d9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
