<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_startDateTime</name>
   <tag></tag>
   <elementGuidId>e604eff3-7495-42b5-8774-9efcde04df9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startDateTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startDateTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd80343b-edcc-44d6-9c09-85baadbb8863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>a751c281-435c-43c7-95c8-643f90741273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ba67b0d9-76c4-491a-8b4c-04317b4ab007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startDateTime</value>
      <webElementGuid>7962064c-efaa-40aa-991f-dd5c05b8f0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDateTime</value>
      <webElementGuid>0a7de945-1ec7-438d-b040-45adc90d2bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9999-12-31</value>
      <webElementGuid>b17ecb75-861a-41c5-a3d1-610a8164c188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startDateTime&quot;)</value>
      <webElementGuid>1b342149-9a20-4045-8176-cf2e2d4d7736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startDateTime']</value>
      <webElementGuid>b6899ba4-5799-430c-9d23-3c6e7120c964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[4]/div/div[2]/div/div/div[2]/div/table/thead/tr[2]/th[3]/span/input</value>
      <webElementGuid>6e78bdee-d665-4701-a958-cfae18b99764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span/input</value>
      <webElementGuid>98b5ce9b-6048-4f82-998b-fcab40e134ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'startDateTime' and @id = 'startDateTime']</value>
      <webElementGuid>4055169c-3b66-490c-bbcd-709d3e42054a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
