<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_endDateTime</name>
   <tag></tag>
   <elementGuidId>a1b7628b-4a76-4f48-b9b2-a6890d5046ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endDateTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endDateTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59f7ee61-6ceb-4c36-ac54-10799dc978ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>3e82cabd-e89e-46b8-9b2d-592570c575ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>3b6ad865-09e7-4a31-a1c3-8742c0250ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>endDateTime</value>
      <webElementGuid>bc6c746e-88f5-40d3-a39c-f12b1f7e8eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endDateTime</value>
      <webElementGuid>648c554f-0cfb-49e1-8b94-21cacf14c999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9999-12-31</value>
      <webElementGuid>c60be84a-ce36-4352-bf38-ef90e263eb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023-11-26</value>
      <webElementGuid>6eedd22c-85ef-4fed-86d6-12fe75dea8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endDateTime&quot;)</value>
      <webElementGuid>3c5d2314-7445-4ebe-a8ec-1b0479d18d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endDateTime']</value>
      <webElementGuid>140a4e48-ddbe-4637-9644-90dddfa6ba66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[4]/div/div[2]/div/div/div[2]/div/table/thead/tr[2]/th[4]/span/input</value>
      <webElementGuid>36a3b652-0fa4-446d-82f3-edf3183ea9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/span/input</value>
      <webElementGuid>182abe2b-55cd-41db-9eb1-ee297f48778b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'endDateTime' and @id = 'endDateTime']</value>
      <webElementGuid>d0bb8239-603c-434b-8975-23db2645392a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
