<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_basePay</name>
   <tag></tag>
   <elementGuidId>e8aeec00-6ae0-45e2-8ec5-4a537d48aa87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basePay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basePay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62237b05-2524-452e-98cf-03221af3d86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>20de73aa-de3a-4ec6-a633-eaf47ad18c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>06927a7c-b1fe-41d2-8bb5-144c40754eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>basePay</value>
      <webElementGuid>a2dcd5e1-fcc1-41af-bb6d-0803ba59a033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Base Pay</value>
      <webElementGuid>52482867-80e6-4b91-a869-2297d923adc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basePay</value>
      <webElementGuid>b4e8671e-ef5c-4a21-b012-d47cff86b341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basePay&quot;)</value>
      <webElementGuid>84e48d86-c4ab-468c-82ce-cd8a2946c679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basePay']</value>
      <webElementGuid>fd13acd5-cf88-4b7f-ae2e-a3464224fc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[3]/span[2]/input</value>
      <webElementGuid>08cf7079-8970-4ed4-b192-b4417fe6a563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]/input</value>
      <webElementGuid>e8fae8a5-3082-48bc-baa6-696807aa83d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'basePay' and @placeholder = 'Base Pay' and @id = 'basePay']</value>
      <webElementGuid>0328e759-e5ff-4843-b9ca-4c68038db40a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
