<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_numberOfAssets</name>
   <tag></tag>
   <elementGuidId>f3b30809-96aa-4a34-b90e-700346548313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberOfAssets</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberOfAssets']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ee7af13-192c-40f9-9d5b-6c3a9f67d38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input tableInput</value>
      <webElementGuid>0fe83176-01ad-4e4f-8bc6-fcc246d17b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ec450b14-cf24-4c5b-8ca6-755c0cc612ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberOfAssets</value>
      <webElementGuid>83b24a93-9b8f-463e-8703-f3db4a118d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Number Of Assets</value>
      <webElementGuid>964cf628-ff98-485c-948a-2689f22658eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberOfAssets</value>
      <webElementGuid>f9829d0e-515a-4ebb-82f7-5e8c6e948f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberOfAssets&quot;)</value>
      <webElementGuid>c99ee8da-749e-4762-bbb9-9f1c9b20dfbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberOfAssets']</value>
      <webElementGuid>0def20b4-d8ae-4de4-88b4-70b90147a0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[4]/div/div[2]/div/div/div[2]/div/table/thead/tr[2]/th/span/input</value>
      <webElementGuid>8154fdb5-d939-4c19-92d1-dcb9c16edd50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/span/input</value>
      <webElementGuid>dd173bd9-9874-47a4-b397-fab32acabf70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'numberOfAssets' and @placeholder = 'Number Of Assets' and @id = 'numberOfAssets']</value>
      <webElementGuid>83e614cb-26be-48a4-b777-4281bf1b3a96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
