<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_identificationNumber</name>
   <tag></tag>
   <elementGuidId>2b91bf6b-14bd-4dd4-be2a-5e6be940771a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identificationNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identificationNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9d97ff3-29cc-486d-8db4-567f85b5fa34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>8d2ad329-30d8-47de-96f8-72a4dcffa6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2a78a7e-b7b4-4d0a-8364-1894634a1f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>0ac3f23b-1276-4baa-a19c-778adec71a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Identification Number</value>
      <webElementGuid>2985ed47-4131-4f44-81f0-b8fb5da98a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>40edd563-c0e2-4b05-80cd-6e3390267bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identificationNumber&quot;)</value>
      <webElementGuid>e565ac3c-e07a-4859-bc1d-7eafd2aa2b44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identificationNumber']</value>
      <webElementGuid>431c449a-162c-44a4-8398-606f60a2a2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[5]/span[2]/input</value>
      <webElementGuid>f90bee66-cb10-44b2-8e53-585bac2e24ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span[2]/input</value>
      <webElementGuid>a8760ee6-2458-49e6-bf7a-59c8de1931b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'identificationNumber' and @placeholder = 'Identification Number' and @id = 'identificationNumber']</value>
      <webElementGuid>2fe00475-3447-418b-848f-c72bed8277b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
