<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectLowMediumHighVery High</name>
   <tag></tag>
   <elementGuidId>e417f5d6-a993-4cda-91ab-da1c57fdbcd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#projectPriorityName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='projectPriorityName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7fcfd968-58ee-412b-8b3c-c999dbf0f0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>4a132cbc-df66-468e-8409-2a5ee0d6984f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>projectPriorityName</value>
      <webElementGuid>0719004c-a86b-4c37-8728-2cb44d246c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>projectPriorityName</value>
      <webElementGuid>377291a1-4e06-4e7d-bf7e-1386711c35ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectLowMediumHighVery High</value>
      <webElementGuid>390ffb0d-e2f5-4e59-bb5d-666105fd01b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projectPriorityName&quot;)</value>
      <webElementGuid>b52338bf-0e0a-4043-82df-2f4009a5136e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='projectPriorityName']</value>
      <webElementGuid>eee38b18-e5db-449f-beb9-6ab5f92cfc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[2]/div/div[3]/span/select</value>
      <webElementGuid>167015d7-95c0-4f1b-8898-dca611671885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/select</value>
      <webElementGuid>f65b1898-10e9-4e89-857c-987529720f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'projectPriorityName' and @id = 'projectPriorityName' and (text() = 'SelectLowMediumHighVery High' or . = 'SelectLowMediumHighVery High')]</value>
      <webElementGuid>92ac4902-2aac-42b8-abf6-af3622377045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
