<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectPayExpense</name>
   <tag></tag>
   <elementGuidId>baa6646e-d20d-4d1a-9ce1-fab74cffa585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='payType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>20394e9a-3cc5-4837-ada9-1facab74b5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>053e55e0-7df1-4fd1-b27a-632c145d040d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payType</value>
      <webElementGuid>57173bea-b0a2-4d25-b078-7f690fd7b0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payType</value>
      <webElementGuid>384c174e-06b7-4624-8114-f7a6a441518a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectPayExpense</value>
      <webElementGuid>c3b0ab0f-5559-4f09-bed8-945ea18c4c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payType&quot;)</value>
      <webElementGuid>a236c48d-f7e0-4d7b-b21c-e1dbda93f035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='payType']</value>
      <webElementGuid>901445f0-e60a-4334-9ec7-827a661716f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[5]/span[2]/select</value>
      <webElementGuid>11507d22-9ffe-4718-ab42-da7e157d6beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span[2]/select</value>
      <webElementGuid>e240a277-f899-4905-8574-f53e9fd37128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'payType' and @id = 'payType' and (text() = 'SelectPayExpense' or . = 'SelectPayExpense')]</value>
      <webElementGuid>1816a1d9-ee47-4b81-a8f5-806b12faeb14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
