<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectLowMediumHighVery High_1</name>
   <tag></tag>
   <elementGuidId>88b7664e-aa89-4797-891d-10cfaf4941d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#priority</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='priority']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cc90ffae-103c-477c-b61b-5828d97b1441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>c1e2b6b4-3605-401b-83f3-a01ff9592b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>priority</value>
      <webElementGuid>c128a742-35ee-4c1b-a3a1-e393a43ad7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priority</value>
      <webElementGuid>ae7096cb-f978-4f53-ac8d-203a00ff264a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectLowMediumHighVery High</value>
      <webElementGuid>632d393e-c3b4-4600-9301-fbf729e83f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;priority&quot;)</value>
      <webElementGuid>edd2540a-82f5-4426-b276-0e989bbf9df9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='priority']</value>
      <webElementGuid>d5431df0-b448-4973-b9aa-5132f4836da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[2]/div/div[3]/span[2]/select</value>
      <webElementGuid>d5db25df-f121-42f1-b7cb-4c19feee5467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/select</value>
      <webElementGuid>ddbe6c70-bfed-43ec-b856-6a07e6168197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'priority' and @id = 'priority' and (text() = 'SelectLowMediumHighVery High' or . = 'SelectLowMediumHighVery High')]</value>
      <webElementGuid>0ebe6136-eb44-4e03-bd3d-5b4802a7e5b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
