<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectHourFlat</name>
   <tag></tag>
   <elementGuidId>7ebc777c-f2f2-49aa-965e-3c1775764ec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='payBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>83d6214a-f286-4a00-b29b-addcac03099f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>2d5e0c79-e04c-4b28-9aa2-891d16b8920e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payBy</value>
      <webElementGuid>7b882acc-c2d1-48e2-92c1-66f36eb2487d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payBy</value>
      <webElementGuid>d02b9980-1cbc-4218-b8dc-6e74614428cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectHourFlat</value>
      <webElementGuid>72d12af6-21a2-49b9-98f9-e2f8b4a02000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payBy&quot;)</value>
      <webElementGuid>0acc2e71-009b-4cb6-89d9-fd78c483c329</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='payBy']</value>
      <webElementGuid>8ff2a14b-c15a-4749-9d05-6743892c69f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[4]/span[2]/select</value>
      <webElementGuid>e3687d31-ff72-4bf1-9fae-912b234bcaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/select</value>
      <webElementGuid>3bfb801a-a27a-4a4d-93a3-1950042c68db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'payBy' and @id = 'payBy' and (text() = 'SelectHourFlat' or . = 'SelectHourFlat')]</value>
      <webElementGuid>0f37b359-77b6-49c4-ad73-c69cfd336b8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
