<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelecttestConstruction Worker Xemplo_9ea524</name>
   <tag></tag>
   <elementGuidId>b9e98752-ff61-4143-a927-55bc86536566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='employeeType.id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4abd010f-ba0a-45fb-91ff-5bab54fc479d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>aeb4b95a-eeea-470d-bf3f-060ad6a7d34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employeeType.id</value>
      <webElementGuid>b5ec5562-e84d-4233-a9b1-27b450c114ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employeeType.id</value>
      <webElementGuid>59fe230f-e820-496a-9611-f3565be6a72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelecttestConstruction Worker Xemployee_458Ironworker UltraIronworker LiteConstruction Worker Maxemployee_851Construction Worker Proh5eOs5hGFlooring Installer ProYVGV37eQTile Setter UltraQ2oqSmAKBrickMasonLOS3iXrGKoushikEmployee1Teacher1actorCivil EngineerConstruction EngineersConstruction EngineerConstruction EOemployee12767Construction_EngineerdferasdConstruction_JE591QAEngineer_402QAEngineer_118QAEngineer_904Master12345Surveyor XSurveyor ProIronworker ProSurveyor LiteEngineerGlazier XConstruction Inspector LiteTile Setter LiteConstruction Inspector ProTile Setter XBrickmason MaxConstruction Inspector UltraBrickmason LiteBrickmason XSurveyor MaxIronworker MaxGlazier LiteSurveyor STile Setter MaxIronworker SSurveyor nBrickmason MMGlazier OTile Setter nSurveyor xxlIronworker OFlooring Installer xxlGlazier bBrickmason MBrickmason lConstruction Inspector lConstruction Worker dConstruction Worker ccGlazier fBrickmason dTile Setter eConstruction Worker aSurveyor bFlooring Installer bBrickmason sSurveyor eConstruction Worker sBrickmason bFlooring Installer MConstruction Inspector dSurveyor aTile Setter bTile Setter ccSurveyor GTile Setter fBrickmason eIronworker GFlooring Installer aConstruction Worker GFlooring Installer eTile Setter sSurveyor DDTile Setter KKSurveyor FFGlazier LLSurveyor KKhfbjemployee_478{{emp_type}}employee127678employeeType_5yepremployeeType_1hgj75employeeType_nrrhfremployeeType_lcdoeemployeeType_lw4w9employeeType_ufke3iemployeeType_bl0v3oemployeeType_lrb5aoemployeeType_gxu5vcemployeeType_t8s7rbemployeeType_ilcmy9employeeType_d6vdg3vemployeeType_v6x58employeeType_dvnjqfemployeeType_te1n1ucraneOperatorManagerTypeemployeeType_8usl1employeeType_i8hh6employeeType_m1o7s9employeeType_ps2etxGlazier CCBrickmason KKConstruction Worker NNemployeeType_j31le9wrok_gvgvemployeeType_6es3n9Flooring Installer KKemployeeType_lr37z9Surveyor LLTile Setter LLemployeeType_bhgo2tConstruction Worker KKIronworker FF FFSurveyor CCTilesMason KKGlazier FFConstruction LLConstruction KKGlazier DDFlooring Installer STile Setter DDTilesMason LLFlooring Installer FFBrickmason LLemployeeType_yapdluInspector LLemployeeType_l5lnhiemployeeType_yr4l22employeeType_ap5bemployeeType_vfzq0semployeeType_jyxyiemployeeType_ibowktemployeeType_6legyemployeeType_lbk2vqemployeeType_yj8repemployeeType_kzoaxemployeeType_ku2bkuemployeeType_w7n0hlemployeeType_na8lghTilesMason CCInspector KKTilesMason DDTilesMason NNTile Setter FFInspector CCFlooring Installer NNTile Setter NNIronworker KKTilesMason SSurveyor NNTilesMason FFBrickmason FFInspector FFInspector DDBrickmason DDemployeeType_4s145jIronworker CCAccountantf63c6cea-f102-4b93-a67b-f59f35b93f2eArchitectd0987d08-d64f-4d09-988f-dfc1a9c2c2eaAccountant566cf078-415d-4a06-a756-eddcbe9f3c49CleanerSweeper{{emp_types}}employee_142employee_452employee1276789employee_586employee_529employee_194employee_445employee_689employee_598employee_497employee_469employee_574employee_694employee_633employee_618employee_236employee_317employee_71employee_907employee_82employee_1000testmanageremployee_437employee_515employee_909employee_135122employee_360employee_256employee_675506employee_605employee_699168employee_955employee_776employee_503employee_311employee_392employee_8employee_331employee_374employee_393employee_926employee_36employee_388employee_385abc333tester123employee_589employee_467employee_303employee_864employee_109employee_95abc1234employee_24employee_757employee_20employee_677employee_553employee_686employee_832Foremanb52a0315-3b1b-4349-a0e7-f76da1cf1f60employee_943employee_728employee_592employee_881123\ManagerQA_ENGINEERDeveloperTeam LeadtesterAMTesterAMrmyx2v49qaabc123Civil Engineera00da68e-00ce-4b00-b9ac-b66e5bbf559aemployee_791employeee_858employeee_283employeee_23employeee_2834employeee_rwpxoemployeee_JmjaELeadLeaderLeadearDriverTester1</value>
      <webElementGuid>3fd9387e-8de8-4e10-be96-e8c5644b1d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeType.id&quot;)</value>
      <webElementGuid>32005071-ea0d-4948-8568-dea445b49429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='employeeType.id']</value>
      <webElementGuid>751f1230-34cd-4f9b-9255-c3422e2aee8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div[4]/span[2]/select</value>
      <webElementGuid>073fd876-88f2-448f-a974-508c8df30d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/select</value>
      <webElementGuid>c25f5bef-ed23-48c5-8282-0b3217a90482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'employeeType.id' and @id = 'employeeType.id' and (text() = 'SelecttestConstruction Worker Xemployee_458Ironworker UltraIronworker LiteConstruction Worker Maxemployee_851Construction Worker Proh5eOs5hGFlooring Installer ProYVGV37eQTile Setter UltraQ2oqSmAKBrickMasonLOS3iXrGKoushikEmployee1Teacher1actorCivil EngineerConstruction EngineersConstruction EngineerConstruction EOemployee12767Construction_EngineerdferasdConstruction_JE591QAEngineer_402QAEngineer_118QAEngineer_904Master12345Surveyor XSurveyor ProIronworker ProSurveyor LiteEngineerGlazier XConstruction Inspector LiteTile Setter LiteConstruction Inspector ProTile Setter XBrickmason MaxConstruction Inspector UltraBrickmason LiteBrickmason XSurveyor MaxIronworker MaxGlazier LiteSurveyor STile Setter MaxIronworker SSurveyor nBrickmason MMGlazier OTile Setter nSurveyor xxlIronworker OFlooring Installer xxlGlazier bBrickmason MBrickmason lConstruction Inspector lConstruction Worker dConstruction Worker ccGlazier fBrickmason dTile Setter eConstruction Worker aSurveyor bFlooring Installer bBrickmason sSurveyor eConstruction Worker sBrickmason bFlooring Installer MConstruction Inspector dSurveyor aTile Setter bTile Setter ccSurveyor GTile Setter fBrickmason eIronworker GFlooring Installer aConstruction Worker GFlooring Installer eTile Setter sSurveyor DDTile Setter KKSurveyor FFGlazier LLSurveyor KKhfbjemployee_478{{emp_type}}employee127678employeeType_5yepremployeeType_1hgj75employeeType_nrrhfremployeeType_lcdoeemployeeType_lw4w9employeeType_ufke3iemployeeType_bl0v3oemployeeType_lrb5aoemployeeType_gxu5vcemployeeType_t8s7rbemployeeType_ilcmy9employeeType_d6vdg3vemployeeType_v6x58employeeType_dvnjqfemployeeType_te1n1ucraneOperatorManagerTypeemployeeType_8usl1employeeType_i8hh6employeeType_m1o7s9employeeType_ps2etxGlazier CCBrickmason KKConstruction Worker NNemployeeType_j31le9wrok_gvgvemployeeType_6es3n9Flooring Installer KKemployeeType_lr37z9Surveyor LLTile Setter LLemployeeType_bhgo2tConstruction Worker KKIronworker FF FFSurveyor CCTilesMason KKGlazier FFConstruction LLConstruction KKGlazier DDFlooring Installer STile Setter DDTilesMason LLFlooring Installer FFBrickmason LLemployeeType_yapdluInspector LLemployeeType_l5lnhiemployeeType_yr4l22employeeType_ap5bemployeeType_vfzq0semployeeType_jyxyiemployeeType_ibowktemployeeType_6legyemployeeType_lbk2vqemployeeType_yj8repemployeeType_kzoaxemployeeType_ku2bkuemployeeType_w7n0hlemployeeType_na8lghTilesMason CCInspector KKTilesMason DDTilesMason NNTile Setter FFInspector CCFlooring Installer NNTile Setter NNIronworker KKTilesMason SSurveyor NNTilesMason FFBrickmason FFInspector FFInspector DDBrickmason DDemployeeType_4s145jIronworker CCAccountantf63c6cea-f102-4b93-a67b-f59f35b93f2eArchitectd0987d08-d64f-4d09-988f-dfc1a9c2c2eaAccountant566cf078-415d-4a06-a756-eddcbe9f3c49CleanerSweeper{{emp_types}}employee_142employee_452employee1276789employee_586employee_529employee_194employee_445employee_689employee_598employee_497employee_469employee_574employee_694employee_633employee_618employee_236employee_317employee_71employee_907employee_82employee_1000testmanageremployee_437employee_515employee_909employee_135122employee_360employee_256employee_675506employee_605employee_699168employee_955employee_776employee_503employee_311employee_392employee_8employee_331employee_374employee_393employee_926employee_36employee_388employee_385abc333tester123employee_589employee_467employee_303employee_864employee_109employee_95abc1234employee_24employee_757employee_20employee_677employee_553employee_686employee_832Foremanb52a0315-3b1b-4349-a0e7-f76da1cf1f60employee_943employee_728employee_592employee_881123\ManagerQA_ENGINEERDeveloperTeam LeadtesterAMTesterAMrmyx2v49qaabc123Civil Engineera00da68e-00ce-4b00-b9ac-b66e5bbf559aemployee_791employeee_858employeee_283employeee_23employeee_2834employeee_rwpxoemployeee_JmjaELeadLeaderLeadearDriverTester1' or . = 'SelecttestConstruction Worker Xemployee_458Ironworker UltraIronworker LiteConstruction Worker Maxemployee_851Construction Worker Proh5eOs5hGFlooring Installer ProYVGV37eQTile Setter UltraQ2oqSmAKBrickMasonLOS3iXrGKoushikEmployee1Teacher1actorCivil EngineerConstruction EngineersConstruction EngineerConstruction EOemployee12767Construction_EngineerdferasdConstruction_JE591QAEngineer_402QAEngineer_118QAEngineer_904Master12345Surveyor XSurveyor ProIronworker ProSurveyor LiteEngineerGlazier XConstruction Inspector LiteTile Setter LiteConstruction Inspector ProTile Setter XBrickmason MaxConstruction Inspector UltraBrickmason LiteBrickmason XSurveyor MaxIronworker MaxGlazier LiteSurveyor STile Setter MaxIronworker SSurveyor nBrickmason MMGlazier OTile Setter nSurveyor xxlIronworker OFlooring Installer xxlGlazier bBrickmason MBrickmason lConstruction Inspector lConstruction Worker dConstruction Worker ccGlazier fBrickmason dTile Setter eConstruction Worker aSurveyor bFlooring Installer bBrickmason sSurveyor eConstruction Worker sBrickmason bFlooring Installer MConstruction Inspector dSurveyor aTile Setter bTile Setter ccSurveyor GTile Setter fBrickmason eIronworker GFlooring Installer aConstruction Worker GFlooring Installer eTile Setter sSurveyor DDTile Setter KKSurveyor FFGlazier LLSurveyor KKhfbjemployee_478{{emp_type}}employee127678employeeType_5yepremployeeType_1hgj75employeeType_nrrhfremployeeType_lcdoeemployeeType_lw4w9employeeType_ufke3iemployeeType_bl0v3oemployeeType_lrb5aoemployeeType_gxu5vcemployeeType_t8s7rbemployeeType_ilcmy9employeeType_d6vdg3vemployeeType_v6x58employeeType_dvnjqfemployeeType_te1n1ucraneOperatorManagerTypeemployeeType_8usl1employeeType_i8hh6employeeType_m1o7s9employeeType_ps2etxGlazier CCBrickmason KKConstruction Worker NNemployeeType_j31le9wrok_gvgvemployeeType_6es3n9Flooring Installer KKemployeeType_lr37z9Surveyor LLTile Setter LLemployeeType_bhgo2tConstruction Worker KKIronworker FF FFSurveyor CCTilesMason KKGlazier FFConstruction LLConstruction KKGlazier DDFlooring Installer STile Setter DDTilesMason LLFlooring Installer FFBrickmason LLemployeeType_yapdluInspector LLemployeeType_l5lnhiemployeeType_yr4l22employeeType_ap5bemployeeType_vfzq0semployeeType_jyxyiemployeeType_ibowktemployeeType_6legyemployeeType_lbk2vqemployeeType_yj8repemployeeType_kzoaxemployeeType_ku2bkuemployeeType_w7n0hlemployeeType_na8lghTilesMason CCInspector KKTilesMason DDTilesMason NNTile Setter FFInspector CCFlooring Installer NNTile Setter NNIronworker KKTilesMason SSurveyor NNTilesMason FFBrickmason FFInspector FFInspector DDBrickmason DDemployeeType_4s145jIronworker CCAccountantf63c6cea-f102-4b93-a67b-f59f35b93f2eArchitectd0987d08-d64f-4d09-988f-dfc1a9c2c2eaAccountant566cf078-415d-4a06-a756-eddcbe9f3c49CleanerSweeper{{emp_types}}employee_142employee_452employee1276789employee_586employee_529employee_194employee_445employee_689employee_598employee_497employee_469employee_574employee_694employee_633employee_618employee_236employee_317employee_71employee_907employee_82employee_1000testmanageremployee_437employee_515employee_909employee_135122employee_360employee_256employee_675506employee_605employee_699168employee_955employee_776employee_503employee_311employee_392employee_8employee_331employee_374employee_393employee_926employee_36employee_388employee_385abc333tester123employee_589employee_467employee_303employee_864employee_109employee_95abc1234employee_24employee_757employee_20employee_677employee_553employee_686employee_832Foremanb52a0315-3b1b-4349-a0e7-f76da1cf1f60employee_943employee_728employee_592employee_881123\ManagerQA_ENGINEERDeveloperTeam LeadtesterAMTesterAMrmyx2v49qaabc123Civil Engineera00da68e-00ce-4b00-b9ac-b66e5bbf559aemployee_791employeee_858employeee_283employeee_23employeee_2834employeee_rwpxoemployeee_JmjaELeadLeaderLeadearDriverTester1')]</value>
      <webElementGuid>e94ba007-79c6-4cde-80f0-3794f62f4216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
