<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>2faa15e4-d230-4843-979c-7f2ab9067370</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#undefined_undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='undefined_undefined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20572e36-de65-4c21-ab3a-6c661b6b8c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cscsButton cscsButton addCscsButton</value>
      <webElementGuid>771df7c7-fe59-4444-9b0d-76902fe5e8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefined_undefined</value>
      <webElementGuid>b32089e0-93bb-4b0a-af73-403c727359ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>5f70916b-1144-4e81-b373-c769e7b8483c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;undefined_undefined&quot;)</value>
      <webElementGuid>b92f2258-5ba2-433f-a20b-e12a525a0e45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='undefined_undefined']</value>
      <webElementGuid>b32a53fc-2375-4291-aa04-fd3139c739e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[3]/div/div/button</value>
      <webElementGuid>c581ec11-9333-4b39-8727-e6ab82d24d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>746b653e-853a-40d9-8c55-3b53f8c27b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'undefined_undefined' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>444cbbf2-c694-4982-bc7b-1b4471ff2e1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
