<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__deviceCode</name>
   <tag></tag>
   <elementGuidId>fbc2c10f-d80d-4da8-91ec-f94209f2bf50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deviceCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='deviceCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2be255d-3576-4b97-9318-04d8548c3f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>8fcd9b1c-1149-45ff-a1be-f77b7328ee5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd4d4f24-ad6e-48f3-ab36-e91b48e06da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deviceCode</value>
      <webElementGuid>388bdb2e-823d-43ca-b9ca-0a9d4d4a220e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Device Code</value>
      <webElementGuid>db6f0c13-30d3-4fb1-aa9c-63371015ebfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deviceCode</value>
      <webElementGuid>61ef7bec-1caa-4e13-8765-120e96a6c56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deviceCode&quot;)</value>
      <webElementGuid>9cf3e529-7deb-460e-a886-8c7477a99dae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='deviceCode']</value>
      <webElementGuid>6f881deb-72b8-41b2-bf58-dda9864d960e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[3]/span[2]/input</value>
      <webElementGuid>f0d774f7-b708-4984-a317-aa923dddf0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]/input</value>
      <webElementGuid>b173888b-cd2c-43ec-a8bb-01a57257df5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'deviceCode' and @placeholder = 'Device Code' and @id = 'deviceCode']</value>
      <webElementGuid>fa6f68df-a701-44b9-98d7-2a3deb1874db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
