<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__identificationNumber</name>
   <tag></tag>
   <elementGuidId>1566f329-8bcc-4fb1-bd8a-2d07c2e05c9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identificationNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identificationNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52f331d3-0ed9-4ec1-b708-dd02ddfbd114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>d8f26dc1-444a-4db5-a4c7-835f780bb225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab0553f5-8871-425e-b6b2-925317070089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>e0ed3f5e-6141-41dc-8f3a-78c98027e57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Identification Number</value>
      <webElementGuid>6c6fe7b9-c3f7-4a06-9bc6-0a539cf7c125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>10888f37-cd28-442e-8379-944d6c19269c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identificationNumber&quot;)</value>
      <webElementGuid>85ebd16e-00c0-4fdd-9061-45c3c6e65f9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identificationNumber']</value>
      <webElementGuid>0f20de6c-1d64-4b6e-937b-4ce58c351f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[5]/span[2]/input</value>
      <webElementGuid>9a73736b-b9a7-4469-b1a5-2ec3ddb5141a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span[2]/input</value>
      <webElementGuid>2d4eff4e-3e8f-4bf6-9a4f-d2ceb65755b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'identificationNumber' and @placeholder = 'Identification Number' and @id = 'identificationNumber']</value>
      <webElementGuid>dc4bf98f-a732-4569-bfd7-6b96fc713ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
