<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Plate Number_plateNumber</name>
   <tag></tag>
   <elementGuidId>114211c8-c494-4be3-8503-48d5d9b504b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#plateNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plateNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45f4093c-5b2f-4e71-8a72-0eb0cfb02754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>39539612-c2bd-4e17-ad8f-16797816d544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70baad04-fd56-43d6-b833-21a771149109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>plateNumber</value>
      <webElementGuid>54933e73-51c5-45e7-bb2a-2411a12ee249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Plate Number</value>
      <webElementGuid>ce4dcf49-deb3-46ea-b42a-7f9e29db2ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plateNumber</value>
      <webElementGuid>4d676c77-f2c4-4735-aa8b-da52e632f8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plateNumber&quot;)</value>
      <webElementGuid>8c1c9597-4f02-4825-9526-b47513a69fca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plateNumber']</value>
      <webElementGuid>b855049f-10ae-46a5-9b42-69884a338375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[4]/span/input</value>
      <webElementGuid>94c2a104-2c2d-406b-8378-3fa3003bdaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/input</value>
      <webElementGuid>488bfcf3-1577-4b82-9749-41bb986b7b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'plateNumber' and @placeholder = 'Plate Number' and @id = 'plateNumber']</value>
      <webElementGuid>9808fb35-49c7-417a-b8ad-4ebacaed1c96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
