<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Copy Text</name>
   <tag></tag>
   <elementGuidId>b45bf61c-c9aa-4317-8190-bd13dd4fe42a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='HTML10']/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HTML10 > div.widget-content > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9dcd6c6b-26f4-4cc1-85a4-410730b5cdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>myFunction1()</value>
      <webElementGuid>5f5ec45f-2d54-4c5c-83cc-a7fc3182eb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy Text</value>
      <webElementGuid>94c78ff8-4936-40be-a0ef-9bddb75307a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HTML10&quot;)/div[@class=&quot;widget-content&quot;]/button[1]</value>
      <webElementGuid>7efc0004-b822-46a9-89d5-98a409492863</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HTML10']/div/button</value>
      <webElementGuid>c4e4aa44-c322-4335-b83a-4b2a2aa4df97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>4766181b-363b-4621-89bc-50bdebd1835c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Copy Text' or . = 'Copy Text')]</value>
      <webElementGuid>71d4dfaf-9e11-4cff-8e2f-5b5f1ff11421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
