<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_sidebarMenuIcon</name>
   <tag></tag>
   <elementGuidId>5a7a842b-5b74-4637-8f3e-8fcb5bf92761</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/aside/div/nav/ul/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.sidebarMenuIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f1246060-7953-482f-b6c7-6f33fc4d3842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebarMenuIcon</value>
      <webElementGuid>5c806a56-cfb3-412c-89cd-35138cf02890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/menu-burger.svg</value>
      <webElementGuid>14324822-4c07-4567-b0e0-fe233a3ffc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>e01f5bde-216d-4767-a66c-47c6f7a627b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>3423b489-c2db-4128-bf7a-ead4f0b6307a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/aside[@class=&quot;ps-sidebar-root ps-collapsed sidebar css-1wvake5&quot;]/div[@class=&quot;ps-sidebar-container css-dip3t8&quot;]/nav[@class=&quot;ps-menu-root css-vj11vy&quot;]/ul[@class=&quot;css-ewdv3l&quot;]/div[@class=&quot;sideHeader&quot;]/img[@class=&quot;sidebarMenuIcon&quot;]</value>
      <webElementGuid>e6996e7c-4225-4bf0-8da4-99df12ccee4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/aside/div/nav/ul/div/img</value>
      <webElementGuid>26d71cbf-26be-40b8-8fff-145e023109fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>38aaea66-c4c1-490c-9d84-3f224c0a2f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/menu-burger.svg']</value>
      <webElementGuid>53df4f95-a0cf-4ccb-9bb6-810b8fa74c4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
