<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_css-honxw6</name>
   <tag></tag>
   <elementGuidId>85afb6a8-ff49-42db-b473-3ea1582a9864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/aside/div/nav[2]/ul/li[7]/a/span[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a16a2ea1-fce0-425a-b54c-6301a61a0f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-honxw6</value>
      <webElementGuid>d6e74fa3-f3cd-4312-b8fd-f7e61185ceea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/aside[@class=&quot;ps-sidebar-root sidebar css-1wvake5&quot;]/div[@class=&quot;ps-sidebar-container css-dip3t8&quot;]/nav[@class=&quot;ps-menu-root css-vj11vy&quot;]/ul[@class=&quot;css-ewdv3l&quot;]/li[@class=&quot;ps-menuitem-root ps-submenu-root css-16jesut&quot;]/a[@class=&quot;ps-menu-button&quot;]/span[@class=&quot;ps-submenu-expand-icon css-1cuxlhl&quot;]/span[@class=&quot;css-honxw6&quot;]</value>
      <webElementGuid>d1adb18a-77fa-41d2-b450-1317ab520ce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/aside/div/nav[2]/ul/li[7]/a/span[3]/span</value>
      <webElementGuid>ba54d42f-61ce-4a71-a7ec-205cf16fb1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/span[3]/span</value>
      <webElementGuid>d61a070a-ba49-444f-86df-66cf1f10f697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
