<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ps-submenu-expand-icon ps-open css-1cuxlhl</name>
   <tag></tag>
   <elementGuidId>8084c23e-47ab-49f6-95c4-51ecb0226252</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/aside/div/nav[2]/ul/li[5]/a/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ps-submenu-expand-icon.ps-open.css-1cuxlhl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c84e153f-d93b-4768-b561-db5216e29cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps-submenu-expand-icon ps-open css-1cuxlhl</value>
      <webElementGuid>81364b33-32c7-45eb-ae04-e350bbd4968d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/aside[@class=&quot;ps-sidebar-root sidebar css-1wvake5&quot;]/div[@class=&quot;ps-sidebar-container css-dip3t8&quot;]/nav[@class=&quot;ps-menu-root css-vj11vy&quot;]/ul[@class=&quot;css-ewdv3l&quot;]/li[@class=&quot;ps-menuitem-root ps-submenu-root ps-open css-16jesut&quot;]/a[@class=&quot;ps-menu-button ps-open&quot;]/span[@class=&quot;ps-submenu-expand-icon ps-open css-1cuxlhl&quot;]</value>
      <webElementGuid>a43a80fb-624f-4e8f-9ab0-0d3c57448032</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/aside/div/nav[2]/ul/li[5]/a/span[3]</value>
      <webElementGuid>661831f0-0cf9-438c-98b6-10e11bced395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span[3]</value>
      <webElementGuid>37dee4b4-37d1-480f-ac40-94794c8201ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
