<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Skip</name>
   <tag></tag>
   <elementGuidId>909867dc-61f6-4b32-8a48-f659117d8a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-1']/event-reminder/div/div/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6841125c-caa0-40c1-b59a-c43ada7e020b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link</value>
      <webElementGuid>ad5e0036-0ff4-4d85-91ce-8032f958a454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Skip</value>
      <webElementGuid>24fdd4ee-38c8-42a5-8b4b-f8a55bbbe6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)/event-reminder[@class=&quot;ng-star-inserted&quot;]/div[1]/div[1]/div[@class=&quot;subscribe-reminder-input&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;text-center m-t-20&quot;]/a[@class=&quot;a-link&quot;]</value>
      <webElementGuid>9a7ad269-408c-4661-9fd5-6c1ce4739907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/event-reminder/div/div/div/div[2]/div[2]/a</value>
      <webElementGuid>a87ea39b-2d2c-43ac-81db-65b7b9cc75e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Skip')]</value>
      <webElementGuid>b51b97e6-2099-417d-9b74-d3bd3be52740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>a659181d-bba8-4e8b-a8be-1df4ff8a48a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Skip' or . = ' Skip')]</value>
      <webElementGuid>daeee318-14df-4bf7-9321-425eea3d7ad0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
