<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_volume_off</name>
   <tag></tag>
   <elementGuidId>766a6451-4967-4552-bb11-280da91eaf90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mute-btn.ng-star-inserted > mat-icon.mat-icon.notranslate.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='es-plr-page']/div/div/app-live-video-player/div/div[2]/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>168213be-1228-4a0c-af41-d1477947f972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87c15a4c-8423-4804-baa8-6be049915681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>46bdb734-68a1-4859-b79b-b6547a0bb5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c6d7c0df-836d-43ad-888e-21539feb19fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>4e6c638c-0cc9-4864-b783-500498d61d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>volume_off</value>
      <webElementGuid>0a1d5318-e1db-4e87-98f2-afd0e2f64c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;es-plr-page&quot;)/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;h-video-play ng-star-inserted&quot;]/app-live-video-player[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;h-video-play video-size-close&quot;]/div[@class=&quot;mute-btn ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>44ce508a-8053-4bd4-a5e0-455bd9b48aa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='es-plr-page']/div/div/app-live-video-player/div/div[2]/mat-icon</value>
      <webElementGuid>73f988cf-a58e-4932-8779-ff807ce76cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-icon</value>
      <webElementGuid>6421908c-5db9-4663-b72c-c67cb35e6ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'volume_off' or . = 'volume_off')]</value>
      <webElementGuid>eebb3531-f896-48a2-a152-eac8a75682c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
