<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>videolive-video-player</name>
   <tag></tag>
   <elementGuidId>ea77bd2c-a669-4235-acd2-f5ea00282784</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#live-video-player</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='live-video-player']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>bac7051f-417b-4be5-8ed8-cbfef5b8f500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>live-video-player</value>
      <webElementGuid>009f6b67-c4c7-4cf3-960b-3b13a8449259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controlslist</name>
      <type>Main</type>
      <value>nofullscreen nodownload</value>
      <webElementGuid>4c9f1e96-fa11-4344-a3cd-eb898dfc9798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngclass.xs</name>
      <type>Main</type>
      <value>v-player-xs</value>
      <webElementGuid>d4175cac-68ca-48ef-9bb8-c0080d7ee89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-player video-size-close</value>
      <webElementGuid>7a6e6759-de2c-4dea-81ba-d72003adf4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>poster</name>
      <type>Main</type>
      <value>https://media.estreamly.com/ivs/v1/592094231790/hTEeIcFOW7PK/2023/11/9/20/0/HUtAdpxZC2wu/media/thumbnails/thumb29.jpg</value>
      <webElementGuid>bf085cf8-cfde-4ac4-87a9-cf3fcff6d4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://estreamly.com/8091eec5-bd3d-4c96-bc01-490ca2006f72</value>
      <webElementGuid>5a36114e-1315-4c5f-8dce-b45200786f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;live-video-player&quot;)</value>
      <webElementGuid>2c1a0f72-4bed-4164-aa07-96b3c39c8521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='live-video-player']</value>
      <webElementGuid>2c870f54-5080-4277-91f1-cb472d2857a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='es-plr-page']/div/div/app-live-video-player/div/div/video</value>
      <webElementGuid>5de86f58-0541-4f7b-8015-f7ef1e517bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>b2ffc741-4914-4823-b05d-dd0940ba103e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'live-video-player' and @src = 'blob:https://estreamly.com/8091eec5-bd3d-4c96-bc01-490ca2006f72']</value>
      <webElementGuid>fb361445-a56d-4626-9260-31d524bd1d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
