<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_deviceCode</name>
   <tag></tag>
   <elementGuidId>9ddfde4e-257e-49d8-94ee-588b01c45db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deviceCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='deviceCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c6c2119-e355-471f-8e4e-7d449512e18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>ae4fc3e9-96d1-4e33-a496-d7af3fb3476e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf3a5f5a-648b-4971-8dd8-113316063d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deviceCode</value>
      <webElementGuid>f4e6cba2-3ed3-4308-b0ec-7f56e69f0c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Device Code</value>
      <webElementGuid>e6fd8d49-fe2d-48ad-b8c7-b67ad435212a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deviceCode</value>
      <webElementGuid>5d326ac6-e6ef-4420-9f1d-8ca9900ea2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deviceCode&quot;)</value>
      <webElementGuid>da7859a3-4a9a-4001-83af-af2bc6bdc000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='deviceCode']</value>
      <webElementGuid>61627bf9-f578-4e5e-aeca-8def7d0c2676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div[3]/span[2]/input</value>
      <webElementGuid>79d2bf19-2886-49e0-bb58-81906d0d1d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]/input</value>
      <webElementGuid>98c46409-5cdf-45ab-b428-2fd2307908d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'deviceCode' and @placeholder = 'Device Code' and @id = 'deviceCode']</value>
      <webElementGuid>50909b26-945c-4328-8e06-4a3a139583de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
