<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_code</name>
   <tag></tag>
   <elementGuidId>a9f2d42a-e38d-4ce3-92d4-88856ab4ca28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b3e0dee-95ae-4298-8af6-35e85b9f73cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>f16e5cb5-e84e-4014-a34b-dfb75390fefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8396984d-1a83-4c9e-a8d5-11cd3fe1362d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>d72e68c9-f31a-43bd-914a-5cbae25deb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>dc2d830f-930e-47f1-a362-9412268ba2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>538685fb-6b71-4908-b347-a894a0b331bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;code&quot;)</value>
      <webElementGuid>fc3a4959-bf56-41b7-8397-96fde0b7d27f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='code']</value>
      <webElementGuid>1effd68d-5751-4e6e-ab0f-e2f752f71f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/span[2]/input</value>
      <webElementGuid>b448f9ba-5af4-4b87-8c52-be6a4fe27a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>cc907fcf-4fb9-4238-95c3-28a94a68c858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code' and @placeholder = 'Code' and @id = 'code']</value>
      <webElementGuid>3425d66c-7c1d-436b-b491-78999b3dd529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
