<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes</name>
   <tag></tag>
   <elementGuidId>8a84bf17-98f8-47e7-ace0-5b62107c5c34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.rrt-button.rrt-ok-btn.toastr-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17a453ae-3231-477a-9f77-e87993f95fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d483efb-ac0a-4ad4-b4af-f0cd5cb39399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rrt-button rrt-ok-btn toastr-control</value>
      <webElementGuid>e051180e-d19c-45c3-aaef-e28a18991210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>e5ed4dfc-81b1-470e-aaa5-e6eb9faeee10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;redux-toastr&quot;]/div[@class=&quot;rrt-confirm-holder&quot;]/div[@class=&quot;rrt-confirm animated bounceIn&quot;]/div[@class=&quot;rrt-buttons-holder&quot;]/button[@class=&quot;rrt-button rrt-ok-btn toastr-control&quot;]</value>
      <webElementGuid>7368507e-8e63-46e0-8ff9-840fae39b1e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>d3b00454-3504-4faa-96a3-4ee990270bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[2]/button</value>
      <webElementGuid>7f27e81f-f752-431a-b4ac-0bc2f1472ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button</value>
      <webElementGuid>4929f31d-bbed-4a8a-bbfd-71f723c6403a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>ff31a455-d789-4595-b71a-5b663ddc4726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
