<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select</name>
   <tag></tag>
   <elementGuidId>812ce30c-149f-44ea-8a2c-27909cc19622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > button.cscsButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='portal']/div/div/div[2]/div[2]/div/div/table/tbody/tr/td/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad2ba8cd-87ec-4e5e-97ed-735be742d2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cscsButton</value>
      <webElementGuid>6dc39235-69d6-4d33-a2cf-028518bd58b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>ebcfc8a6-3a36-45bf-957a-4358594d7ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portal&quot;)/div[@class=&quot;ModalContainer&quot;]/div[@class=&quot;ModalWrapper&quot;]/div[@class=&quot;ModalContent&quot;]/div[@class=&quot;modal_selectTable tableContainer&quot;]/div[@class=&quot;outer-wrapper&quot;]/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;table table-hover&quot;]/tbody[1]/tr[1]/td[1]/button[@class=&quot;cscsButton&quot;]</value>
      <webElementGuid>5ff33ef6-9689-4770-beac-55c2109d5830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portal']/div/div/div[2]/div[2]/div/div/table/tbody/tr/td/button</value>
      <webElementGuid>d829bf0b-8ff3-4d27-b39c-8088a6d169a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>d793849f-945f-4a7b-9813-b0ad221f562f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>5a433c68-c838-4f7e-924c-f991c3dafe7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
