<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add_1</name>
   <tag></tag>
   <elementGuidId>c13eb869-6ed1-4dc5-b5f9-fafc108ff7ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.saveButtonWrapper > div > #undefined_undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='undefined_undefined'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d162c173-3e89-4ffc-beab-130fdd390a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cscsButton cscsButton addCscsButton</value>
      <webElementGuid>c73c65be-b8a1-44b7-aa1a-27b5b9773b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>undefined_undefined</value>
      <webElementGuid>b2161661-c2e4-4836-9b8d-b6b0ea23612b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>5cfc7d73-f05c-4ab6-b6eb-40f2f1b5e3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/div[@class=&quot;sidePage&quot;]/div[@class=&quot;sidebody&quot;]/div[@class=&quot;saveButtonContainer mb-1&quot;]/div[@class=&quot;saveButtonWrapper&quot;]/div[1]/button[@id=&quot;undefined_undefined&quot;]</value>
      <webElementGuid>a8dfa7bd-1c82-4959-a6c0-fc4f88997316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='undefined_undefined'])[3]</value>
      <webElementGuid>b436e20f-851e-4c1d-b2b8-db62044728c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[5]/div/div/button</value>
      <webElementGuid>99a06dd4-7393-4de2-9965-e68963ab85b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/button</value>
      <webElementGuid>6c228823-fe88-4cbf-b407-d72ee371295e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'undefined_undefined' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>63dc1e15-7493-48c6-9aa3-48784dc5f487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
