<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_plannedCost</name>
   <tag></tag>
   <elementGuidId>97133b10-f832-4f7c-9870-03615468f629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#plannedCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plannedCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aeab26aa-6c07-4e50-bee8-5ba69974d38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input tableInput</value>
      <webElementGuid>ba26b67a-306b-4b5c-9359-db2cc2b83409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>982544c4-7d93-45af-a459-fb2b07919a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>plannedCost</value>
      <webElementGuid>279b4bd9-fb95-4053-a1b5-402eedab1908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Planned Asset Cost</value>
      <webElementGuid>f4e838c2-1f07-42c6-a3af-ae99773f910b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plannedCost</value>
      <webElementGuid>65d0d66d-aab1-4226-b4af-92ca6f724086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plannedCost&quot;)</value>
      <webElementGuid>863fd690-f500-4073-8484-370872483083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plannedCost']</value>
      <webElementGuid>b5471a33-d398-43e2-8804-7ed6f5308e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[4]/div/div[2]/div/div/div[2]/div/table/thead/tr[2]/th[5]/span/input</value>
      <webElementGuid>78376607-49b5-4c73-8aa5-44e08c084fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/span/input</value>
      <webElementGuid>665512f0-ef92-454e-aaac-128031e1cd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'plannedCost' and @placeholder = 'Planned Asset Cost' and @id = 'plannedCost']</value>
      <webElementGuid>89edf4a9-6b57-42a5-9741-009759ab7e7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
