<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_numberOfAssets</name>
   <tag></tag>
   <elementGuidId>c6092a85-9a60-4b78-9278-352da661a874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberOfAssets</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberOfAssets']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>167ae3af-04fe-404f-a913-d13a19423086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input tableInput</value>
      <webElementGuid>2bf265cc-5f09-4634-b3ba-8cb36c9adc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>07b622ca-3310-467b-8f45-b9e0c38ab669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberOfAssets</value>
      <webElementGuid>26e4a6f2-92cb-4703-b55b-e4e8efed867f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Number Of Assets</value>
      <webElementGuid>ba8b3bfb-2c7d-405c-8493-c802a60344e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberOfAssets</value>
      <webElementGuid>f9df0224-4fb7-4310-844d-cf057b694c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberOfAssets&quot;)</value>
      <webElementGuid>f460b043-6d7c-435b-b637-9efd304daece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberOfAssets']</value>
      <webElementGuid>2e21187c-7afb-4bb9-a090-1884340b6eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[4]/div/div[2]/div/div/div[2]/div/table/thead/tr[2]/th/span/input</value>
      <webElementGuid>da2b2f41-9eae-4ef9-8893-5d10a1390de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/span/input</value>
      <webElementGuid>bcc74460-5364-4901-92df-c2fc5b14683a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'numberOfAssets' and @placeholder = 'Number Of Assets' and @id = 'numberOfAssets']</value>
      <webElementGuid>8e0d06ee-ed64-4f6d-9854-b38bfe561d41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
