<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_plannedEstimateCost</name>
   <tag></tag>
   <elementGuidId>5a645c50-6f8b-4f19-a53b-a7ecc6dbdb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#plannedEstimateCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plannedEstimateCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4ada7f2-e9fb-4130-8976-418eeb23b4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>b7a4ecf8-5ab6-45e7-b62f-449907bab510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e03804f2-d6b2-4f22-9535-564c429ce182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>plannedEstimateCost</value>
      <webElementGuid>00916480-09d7-48d5-9033-b6850be6f8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Planned Cost</value>
      <webElementGuid>8ce4643f-8f43-4286-a170-2ca28f95c072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plannedEstimateCost</value>
      <webElementGuid>54c8cb0e-528e-4c1c-bde9-8229ee27290f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plannedEstimateCost&quot;)</value>
      <webElementGuid>43dda176-ee2f-41f4-9aa6-ff743d57619f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plannedEstimateCost']</value>
      <webElementGuid>5d4782c6-9b97-4615-ab79-413eb844c50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[2]/div/div[8]/span[2]/input</value>
      <webElementGuid>26c8e9e2-a4bd-4712-95d6-f55d8a3da271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span[2]/input</value>
      <webElementGuid>79875ce0-50ff-4e78-8c42-9d33122a3640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'plannedEstimateCost' and @placeholder = 'Planned Cost' and @id = 'plannedEstimateCost']</value>
      <webElementGuid>27bbbabd-62d1-4675-807e-d72b6fdbda88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
