<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectLowMediumHighVery High</name>
   <tag></tag>
   <elementGuidId>9e30db77-eb27-4807-b49a-5b17ccd8acfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#projectPriorityName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='projectPriorityName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2497758a-f887-484c-a219-fd8aca055c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>39c5947d-2d9c-498a-b425-94a240aaa390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>projectPriorityName</value>
      <webElementGuid>87ccd754-623b-4897-ba91-86f32f5bc6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>projectPriorityName</value>
      <webElementGuid>8a35498d-0cea-4c57-b3b5-ad1d11dd5277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectLowMediumHighVery High</value>
      <webElementGuid>e1da330d-dfd4-4959-a0a0-dd63252b2067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projectPriorityName&quot;)</value>
      <webElementGuid>3345f391-11cc-4e25-8c39-a2ceddfb698b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='projectPriorityName']</value>
      <webElementGuid>a7c4c733-f063-44ab-b3f5-92199cfd1500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[2]/div/div[3]/span/select</value>
      <webElementGuid>c3c50ca5-afce-47e7-8f43-0016c50e31af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/select</value>
      <webElementGuid>01a5e738-685f-4bb6-8154-1774a32570cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'projectPriorityName' and @id = 'projectPriorityName' and (text() = 'SelectLowMediumHighVery High' or . = 'SelectLowMediumHighVery High')]</value>
      <webElementGuid>e935f342-e504-4956-b52a-aed61c042d82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
