<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_business-logo</name>
   <tag></tag>
   <elementGuidId>38f820e3-1a19-4751-a52e-349338f6d291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.business-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bodyContainer']/app-watch/div/section/div/swiper/div[2]/div/div/div[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a44bfa2-2eee-4d73-8b8b-00c45c9d7fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>business-logo</value>
      <webElementGuid>9e50c68e-1f56-4825-8580-1b69db746723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>91f5bd9c-9d76-459a-86a5-7fb08065f7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://streamifyimages-stg.s3.amazonaws.com/Business/novica/image/X4gMn_2019_NOVICAImpact.jpg</value>
      <webElementGuid>3d5151ab-e836-48fe-8802-d509fade1cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyContainer&quot;)/app-watch[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;watch-page&quot;]/section[@class=&quot;latest-shows p-0&quot;]/div[1]/swiper[@class=&quot;swiper swiper-initialized swiper-horizontal swiper-pointer-events swiper-backface-hidden&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide ng-star-inserted swiper-slide-active&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;post-info&quot;]/div[1]/div[1]/img[@class=&quot;business-logo&quot;]</value>
      <webElementGuid>99a2caaf-3869-4364-94e9-e2c99501f719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyContainer']/app-watch/div/section/div/swiper/div[2]/div/div/div[4]/div/div/img</value>
      <webElementGuid>014b524a-0028-4213-a4bc-602c9af3f19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://streamifyimages-stg.s3.amazonaws.com/Business/novica/image/X4gMn_2019_NOVICAImpact.jpg')]</value>
      <webElementGuid>bf32fc40-afe6-4a22-af52-d9afbc09896e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[4]/div/div/img</value>
      <webElementGuid>2157c645-2a43-4f68-a364-92f1edd71782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://streamifyimages-stg.s3.amazonaws.com/Business/novica/image/X4gMn_2019_NOVICAImpact.jpg']</value>
      <webElementGuid>e5b568e2-9771-4418-81f0-69e1d2019399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
