<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Visible After 5 Seconds</name>
   <tag></tag>
   <elementGuidId>7a49444c-de54-41ec-8f0f-5e02c67c9c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='visibleAfter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visibleAfter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>295bbca2-6f55-432a-8661-4178ff79ccbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visibleAfter</value>
      <webElementGuid>840bbec9-6eee-432c-b423-6fa4279d79c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>313f6ae5-cde6-41e5-9a0a-bf821bc4b86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-4 btn btn-primary</value>
      <webElementGuid>6009e1d6-00bb-436c-a2ba-2473d8a2e1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visible After 5 Seconds</value>
      <webElementGuid>b619d512-29c8-44d3-a57e-f47a0dbc3490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visibleAfter&quot;)</value>
      <webElementGuid>a50a4f5c-9b3b-49cf-812a-04a41b6fa5b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='visibleAfter']</value>
      <webElementGuid>571b9472-295e-4fac-9b58-f92769d50e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/button[3]</value>
      <webElementGuid>30ed30a3-b75b-4b01-b25f-35fca58f64e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>783d9657-ddae-4033-b249-d8b3f9800b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'visibleAfter' and @type = 'button' and (text() = 'Visible After 5 Seconds' or . = 'Visible After 5 Seconds')]</value>
      <webElementGuid>931265fa-e25e-4a45-b4ab-468bc067ae20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
