<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>763a7b9d-00e6-435a-b354-ef6567d803a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bodyContainer']/app-watch/div/section/div/swiper/div[2]/div[2]/div/div[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swiper-slide.ng-star-inserted.swiper-slide-next > div.ng-star-inserted > div.shows-play-btn > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4365a97b-3650-43dc-b7e0-a1148049bc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../assets/images/play icon.png</value>
      <webElementGuid>1aa85ad7-685e-44cb-8808-8fa254b26e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>dafa0634-1032-4e42-8fe9-32568094af0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyContainer&quot;)/app-watch[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;watch-page&quot;]/section[@class=&quot;latest-shows p-0&quot;]/div[1]/swiper[@class=&quot;swiper swiper-initialized swiper-horizontal swiper-pointer-events swiper-backface-hidden&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide ng-star-inserted swiper-slide-next&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;shows-play-btn&quot;]/img[1]</value>
      <webElementGuid>3af7edaf-f02c-4106-aac9-c1ebab7ec26f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyContainer']/app-watch/div/section/div/swiper/div[2]/div[2]/div/div[3]/img</value>
      <webElementGuid>5334c05b-9ec0-46f4-8dee-38740bedaf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/img</value>
      <webElementGuid>476a5c0b-8c4c-4b93-b005-3278239f1e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../assets/images/play icon.png']</value>
      <webElementGuid>a5548951-1340-49f7-8048-171f7303d011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
