<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>07520f6d-2903-42cb-a7ef-ed2dbad43fc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.shows-play-btn > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bodyContainer']/store-comp/div/div/div[3]/div/previously-live/div/swiper/div[3]/div/div/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fd40eaa9-f988-4f38-a26c-e9a1948d31d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../assets/images/play icon.png</value>
      <webElementGuid>c635c6e4-3a46-4595-ad50-e11a2f1e0074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>ac1b43c7-596b-4dde-aa29-b6564b5b1d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bodyContainer&quot;)/store-comp[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;store&quot;]/div[@class=&quot;store-content&quot;]/div[@class=&quot;content ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/previously-live[1]/div[@class=&quot;previouly-live&quot;]/swiper[@class=&quot;swiper swiper-initialized swiper-horizontal swiper-pointer-events&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide ng-star-inserted swiper-slide-active&quot;]/div[@class=&quot;previouly-swiper ng-star-inserted&quot;]/div[@class=&quot;shows-play-btn&quot;]/img[1]</value>
      <webElementGuid>fedbb774-ebee-416f-a5bd-baa1bb0538f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyContainer']/store-comp/div/div/div[3]/div/previously-live/div/swiper/div[3]/div/div/div[3]/img</value>
      <webElementGuid>4904f136-0588-4030-b201-50fbc5dabef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>3e742f3f-deab-48b5-9a4a-0db42977ace9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../assets/images/play icon.png']</value>
      <webElementGuid>28161ed1-a94e-4e91-89da-8217d5b15dfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
