<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_We use cookies We use _8180f3</name>
   <tag></tag>
   <elementGuidId>bd9e8052-9ae3-4978-a3ef-d428f1a9081d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>ebf1e0f6-d675-4cc6-b4a9-e25258889a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>943311ef-76c9-49f9-bfcc-979ff7c7432b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container cdk-dialog-container ng-tns-c48-2 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>adeef75b-a80d-4d43-be21-d8999d89233d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-0</value>
      <webElementGuid>556fdb09-cff5-4e46-97a7-d4ad7f418e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>63469758-fc69-435f-9cbc-f4512afb9092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-0</value>
      <webElementGuid>b9ee59e4-970f-4e40-9500-9dc391f41c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We use cookies We use (yummy) cookies that are necessary to deliver the best browsing experience. By using our website, you agree to the use of cookies. By accepting, you additionally agree to the usage of marketing cookies. cookieAcceptcancel</value>
      <webElementGuid>505ad60d-6384-4aa1-81e3-56e28e6aba39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)</value>
      <webElementGuid>9ea2e66e-99d8-4b05-9dcf-46420b09d548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      <webElementGuid>db7d59a5-8d44-4f9b-b179-5b3f4cdca525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/mat-dialog-container</value>
      <webElementGuid>eedc5cc6-bafb-4c1c-9d75-961f672d4be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>b16289e7-f14a-4507-ad32-7609d0ab60b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-0' and (text() = 'We use cookies We use (yummy) cookies that are necessary to deliver the best browsing experience. By using our website, you agree to the use of cookies. By accepting, you additionally agree to the usage of marketing cookies. cookieAcceptcancel' or . = 'We use cookies We use (yummy) cookies that are necessary to deliver the best browsing experience. By using our website, you agree to the use of cookies. By accepting, you additionally agree to the usage of marketing cookies. cookieAcceptcancel')]</value>
      <webElementGuid>fe7b02ea-7e6f-4b24-95c5-1030b17cf918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
