<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>videolive-video-player-previouly-live0</name>
   <tag></tag>
   <elementGuidId>ce1857a9-7094-4fde-bbbe-0e5f8d72988e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#live-video-player-previouly-live0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='live-video-player-previouly-live0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>2bf1e3f5-390d-422a-972f-628a8fe49aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>video-content-previouly-live</value>
      <webElementGuid>fab647b2-be09-4f8d-9905-a914db31cef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>live-video-player-previouly-live0</value>
      <webElementGuid>731352a8-33a5-40d0-934c-e7791f32b92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>poster</name>
      <type>Main</type>
      <value>https://media.estreamly.com/ivs/v1/592094231790/hTEeIcFOW7PK/2023/11/9/20/0/HUtAdpxZC2wu/media/thumbnails/thumb29.jpg</value>
      <webElementGuid>32318076-6e83-46f4-bc3c-c47fc50cc5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://estreamly.com/a77e2a6a-4aa7-4e26-a12b-3e2a587e9ee0</value>
      <webElementGuid>c11b52a2-5451-4a24-9ef6-c7b601b6e326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;live-video-player-previouly-live0&quot;)</value>
      <webElementGuid>bfa5f846-a6bb-4730-89ed-80194d65afa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='live-video-player-previouly-live0']</value>
      <webElementGuid>12b71c7c-0466-4169-86e2-17eab4beafe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bodyContainer']/store-comp/div/div/div[3]/div/previously-live/div/swiper/div[3]/div/div/div[2]/video</value>
      <webElementGuid>1a560b18-918b-4341-950b-f756c624879e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>0a5bdcc4-7d7b-4269-b14c-0a9aea40006c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'live-video-player-previouly-live0' and @src = 'blob:https://estreamly.com/a77e2a6a-4aa7-4e26-a12b-3e2a587e9ee0']</value>
      <webElementGuid>c3c54e09-fc62-4ee9-88f1-38d01236b956</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
