<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please select a project.DJF, Mr.DJF, Mr</name>
   <tag></tag>
   <elementGuidId>76af3a39-88ad-4653-8e6b-70546acd2a11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.projetWrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>893a8650-58a4-4fc2-bd88-74c5d4f41548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>projetWrapper</value>
      <webElementGuid>9bf1f82c-3143-4ba7-9629-6af947707174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select a project.DJF, Mr.DJF, Mr.</value>
      <webElementGuid>7dbb8cd5-1918-4ced-bed3-63c458a492db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/div[@class=&quot;sidePage&quot;]/div[@class=&quot;sidebody&quot;]/div[@class=&quot;assetAssignment-container&quot;]/div[@class=&quot;projetWrapper&quot;]</value>
      <webElementGuid>3947a014-e05e-4829-875d-8e38c068ae44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>9de2d7e6-50e5-4b40-ad2b-1b8db00074b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]</value>
      <webElementGuid>c4fbe96f-3c46-496d-80bb-3ed72e456dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Please select a project.DJF, Mr.DJF, Mr.' or . = 'Please select a project.DJF, Mr.DJF, Mr.')]</value>
      <webElementGuid>9c235583-76b5-4caa-b0ee-c071b4823e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
