<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DJF, Mr_1</name>
   <tag></tag>
   <elementGuidId>780428ee-d5bf-4237-adbb-7580cd80ef62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dateSelectorContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f33fd325-dde6-4a6d-8794-0c6897429e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dateSelectorContainer</value>
      <webElementGuid>9492824c-2c13-47c5-ba00-9a262ad916db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DJF, Mr.</value>
      <webElementGuid>fd6d42a7-1d9c-46fc-a9f7-c63fd96ebc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/div[@class=&quot;sidePage&quot;]/div[@class=&quot;sidebody&quot;]/div[@class=&quot;assetAssignment-container&quot;]/div[@class=&quot;projetWrapper&quot;]/div[@class=&quot;dateSelectorContainer&quot;]</value>
      <webElementGuid>bccae1a6-f4c0-43b6-a2b2-ca41119f8de1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>dbab3433-e3ab-4ffb-a5dd-6e3aaca41d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>78c430ea-ad98-49c7-a514-199583282a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DJF, Mr.' or . = 'DJF, Mr.')]</value>
      <webElementGuid>5d11cd28-ccdb-4535-8224-066c87f49e05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
