<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectLowMediumHighVery High</name>
   <tag></tag>
   <elementGuidId>e5f1fee0-43e2-4199-a81b-6b8358d8e4ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#projectPriorityName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='projectPriorityName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d32e63a1-4ac7-42c9-a593-8fc2a26a55da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input</value>
      <webElementGuid>47b49ec3-1ad6-4958-8a46-7f5810e783b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>projectPriorityName</value>
      <webElementGuid>cca6a4e9-c8b8-4941-9490-a9ecbbba8bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>projectPriorityName</value>
      <webElementGuid>3931710d-10cd-4f52-bcee-c0372780b551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectLowMediumHighVery High</value>
      <webElementGuid>89763b24-8d84-4641-865d-89bf483b5906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projectPriorityName&quot;)</value>
      <webElementGuid>b1672b9f-2deb-4daa-b360-1f5938578ba6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='projectPriorityName']</value>
      <webElementGuid>6ed4f33e-b032-47f4-aaf3-185623b9bbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div[2]/div/div[3]/span/select</value>
      <webElementGuid>79922ad4-8ea6-4e9a-a71f-f5234dbbaa4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/select</value>
      <webElementGuid>ab0e9cb8-a543-40f0-ad3f-8804fe57ee8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'projectPriorityName' and @id = 'projectPriorityName' and (text() = 'SelectLowMediumHighVery High' or . = 'SelectLowMediumHighVery High')]</value>
      <webElementGuid>db14cf49-1f1b-4e2b-b7f9-909f62b54d62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
