<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_keyboard_arrow_up</name>
   <tag></tag>
   <elementGuidId>505632d8-536a-44c9-92e0-95bf32d52b7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='es-plr-page']/div/div/app-live-video-player/div/div[4]/div/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.icn > mat-icon.mat-icon.notranslate.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>4bdbeee4-5f55-45c8-89a8-f2e37e7297e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1c6a9f2b-c119-43f3-83ee-aa3c940d9dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>ed75750a-0bbb-4872-b09d-6997b6d3ea0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a8e1ac3a-9820-4f77-9d05-c18490c8e543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>0e5a1f26-600a-4922-a2b6-fc201c1e9785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>keyboard_arrow_up</value>
      <webElementGuid>e00ac89a-d3b2-4a9e-a7df-69cbc37cc493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;es-plr-page&quot;)/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;h-video-play ng-star-inserted&quot;]/app-live-video-player[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;h-video-play video-size-close&quot;]/div[@class=&quot;change-video-options ng-star-inserted&quot;]/div[@class=&quot;icn&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>17e0120a-f693-46be-97c8-9ab5494213e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='es-plr-page']/div/div/app-live-video-player/div/div[4]/div/mat-icon</value>
      <webElementGuid>64806dd9-6d8a-4915-a7d5-50cd3cbf31dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/mat-icon</value>
      <webElementGuid>267536d8-7c41-4ef6-9b2a-3a1852dc51f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'keyboard_arrow_up' or . = 'keyboard_arrow_up')]</value>
      <webElementGuid>9e865a54-1e3f-4ced-bb8e-19738b9770c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
