<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_projectType</name>
   <tag></tag>
   <elementGuidId>7ca1d27f-cdb9-414b-9c7c-8a618d510cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#projectType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='projectType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0125b26d-3252-4309-ad46-7b083e8c9869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom_input tableInput</value>
      <webElementGuid>df07aad2-d518-4154-bc93-d5881b2bbbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f50c1c19-b0ef-47de-9c87-990f18c4a78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>projectType</value>
      <webElementGuid>292cc959-6ddf-46d3-a481-f6946867af60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Project Type</value>
      <webElementGuid>effa01ad-8135-4b0f-adf3-0ba00d7862ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>projectType</value>
      <webElementGuid>b9cb6391-5a5e-46dc-b559-8662cbfb6b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projectType&quot;)</value>
      <webElementGuid>a9b12f77-7bdf-4350-92fd-216b1a5ae1b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='projectType']</value>
      <webElementGuid>1044e6dc-59c1-4899-aec7-cb6b3e55efee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div/div[2]/div/table/thead/tr[2]/th[3]/span/input</value>
      <webElementGuid>7af8fbae-97b1-4807-91e6-27f311847eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span/input</value>
      <webElementGuid>c2054312-c140-401d-98ad-f3a1d3068e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'projectType' and @placeholder = 'Project Type' and @id = 'projectType']</value>
      <webElementGuid>67d27609-3a32-497f-b2c1-1c5044fce810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
