<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Draw a polygon</name>
   <tag></tag>
   <elementGuidId>bd02f2ff-e619-4f1d-9579-1fbb7cb1977d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.leaflet-draw-draw-polygon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9a26d9d5-b767-44c9-8ab9-405028e7ffa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-draw-draw-polygon</value>
      <webElementGuid>43bcb27a-9d81-4994-b3bf-c4d89cd6c121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>33992996-9c7e-4639-8e65-6623c09c55b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Draw a polygon</value>
      <webElementGuid>e992c93d-d59a-4668-ba1b-2c35e64b0483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draw a polygon</value>
      <webElementGuid>daebe636-4d46-427c-98d3-3e14bea86614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/div[@class=&quot;sidePage&quot;]/div[@class=&quot;sidebody&quot;]/div[1]/div[@class=&quot;borderWrapper&quot;]/div[@class=&quot;leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom&quot;]/div[@class=&quot;leaflet-control-container&quot;]/div[@class=&quot;leaflet-top leaflet-right&quot;]/div[@class=&quot;leaflet-draw leaflet-control&quot;]/div[@class=&quot;leaflet-draw-section&quot;]/div[@class=&quot;leaflet-draw-toolbar leaflet-bar leaflet-draw-toolbar-top&quot;]/a[@class=&quot;leaflet-draw-draw-polygon&quot;]</value>
      <webElementGuid>0965fd9e-d2c1-4827-a12d-e19716281c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div/div/a</value>
      <webElementGuid>003bb801-2f7e-4e79-9d73-d98526e05c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>f3c32cb2-ea02-4493-a608-dc3dde9fce81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/a</value>
      <webElementGuid>850158a9-5686-4214-87ef-d2f5a856e8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Draw a polygon' and (text() = 'Draw a polygon' or . = 'Draw a polygon')]</value>
      <webElementGuid>1b1babb2-e4bf-4b86-8fe4-d4d5852a3cc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
