<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add Geofence Name Edit layersDelete lay_764550</name>
   <tag></tag>
   <elementGuidId>1fc278ad-6eff-47e2-865a-baf565376fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sidebody</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>389756f3-c77e-4780-bb88-6c35b99145f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebody</value>
      <webElementGuid>71842f62-fc71-4010-bace-eebf77d11ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Geofence Name *+−Edit layersDelete layers Leaflet | © OpenStreetMapAdd</value>
      <webElementGuid>deb87982-8def-4a39-b2c9-ea4ddbf6de7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[1]/div[1]/div[@class=&quot;sideContainer&quot;]/div[@class=&quot;sidePage&quot;]/div[@class=&quot;sidebody&quot;]</value>
      <webElementGuid>3e239aa2-0d24-49b4-b22b-9b740dd4d000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div[2]</value>
      <webElementGuid>aeeaa12e-496b-44eb-b937-48f0bf53c5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>c642c999-ea60-4811-aeda-983cf160bbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add Geofence Name *+−Edit layersDelete layers Leaflet | © OpenStreetMapAdd' or . = 'Add Geofence Name *+−Edit layersDelete layers Leaflet | © OpenStreetMapAdd')]</value>
      <webElementGuid>00e59ac3-a069-4e8f-b82c-be06bff25473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
