<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>857ba7ec-ff0c-4b69-b031-d15b36572f25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div/div/div[3]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.close-toastr.toastr-control > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bbc8aef0-2472-4382-8290-51c78b079448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>✕</value>
      <webElementGuid>723e49b1-43e5-4d87-a7be-5a524d7841f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;redux-toastr&quot;]/div[1]/div[@class=&quot;top-right&quot;]/div[1]/div[@class=&quot;toastr animated rrt-error&quot;]/div[1]/div[@class=&quot;rrt-right-container&quot;]/div[@class=&quot;close-toastr toastr-control&quot;]/span[1]</value>
      <webElementGuid>8c196287-2b85-4b79-8793-21abc19d677e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div/div/div[3]/div/span</value>
      <webElementGuid>ca4c9f33-4140-42f4-a508-24763fa5ff80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/span</value>
      <webElementGuid>36c869f2-43a2-406b-b09e-f6e81836acf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '✕' or . = '✕')]</value>
      <webElementGuid>23ed0449-6011-4e10-87e7-c784c06c3c63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
