<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Podcast</name>
   <tag></tag>
   <elementGuidId>24f9c1dc-a236-4fba-9e82-0359c7bc99e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-671 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-671']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>512afe29-746d-409e-a352-6b0f5cd96265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://get.estreamly.com/podcast/</value>
      <webElementGuid>c4be3610-6eac-4c06-b85d-0c2997376e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Podcast</value>
      <webElementGuid>035de6f9-ffca-4727-816a-0a8d1ba036dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-671&quot;)/a[1]</value>
      <webElementGuid>32de0aa8-4ff8-4235-a076-fb3122f62e04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-671']/a</value>
      <webElementGuid>4b15e9b9-c518-4586-8c7d-92173fc7fab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Podcast')]</value>
      <webElementGuid>3fe34fc8-cd33-4569-a27a-45a83965f649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://get.estreamly.com/podcast/')]</value>
      <webElementGuid>0c2f50f6-e890-4714-97c2-c867c9b39d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>f12828bd-ee28-4e1e-9a83-bde8e2fd853c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://get.estreamly.com/podcast/' and (text() = 'Podcast' or . = 'Podcast')]</value>
      <webElementGuid>266e0d81-12bc-4a4c-bf49-62a30e50e7f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
